#!/usr/bin/env python3
"""Status map of the README: two DDI coverage metrics, measured from the source, drawn as treemaps.

Metrics
-------
kmd-ddi    Every function slot of DRIVER_INITIALIZATION_DATA (WDK 10.0.26100, km/dispmprt.h), against the slots
           that WddmBuildTable (driver/kmd/wddm.c), the table of the full WDDM driver, fills with a function that
           does work.
d3d12-ddi  Every function slot of the tables that the D3D12 user-mode driver gives the runtime (the adapter table
           of OpenAdapter12 and the tables of FillDDITable, at the DDI build it reports), against the slots whose
           function does work.

The rule for "done" is the same for both and is in RULE below. It is a static reading of the source: no build and no
lab. A slot is judged by the function that the table stores. A function whose only work is one call to another
function of the same driver is judged by that function.

Outputs (all under docs/status/): status.json (every slot, its function, source line and verdict), one treemap SVG
per metric, one badge SVG per metric, and the block between the status-map markers of README.md.

  python tools/docs/status_map.py --kits <WDK nuget dir>     write the outputs
  python tools/docs/status_map.py --kits <dir> --check       exit 1 when a committed output differs from a fresh run

Without --kits (and without BC250_KITS) the slot lists of the two WDK structures come from the committed
status.json, whose header hashes say which header they were read from. The verdicts are always measured again.
Standard library only.
"""
from __future__ import annotations

import argparse
import hashlib
import html
import json
import math
import os
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT_DIR = REPO / "docs" / "status"
JSON_PATH = OUT_DIR / "status.json"
README = REPO / "README.md"
BEGIN = "<!-- status-map (generated by tools/docs/status_map.py, do not edit) -->"
END = "<!-- /status-map -->"
WDK_VERSION = "10.0.26100.0"
KMD_HEADER = "km/dispmprt.h"
VERSION_HEADER = "shared/d3dukmdt.h"
UMD_HEADER = "um/d3d12umddi.h"

RULE = [
    "A slot is done when the table stores a function in it and that function does work.",
    "A function does no work when no return statement can return success: every return gives a failure constant "
    "(E_NOTIMPL, STATUS_NOT_SUPPORTED, STATUS_UNSUCCESSFUL and the other names in REFUSAL).",
    "A function does no work when it only logs, counts, takes locks, reads state, reports an error or writes zeros: "
    "no call outside NEUTRAL and no write of a nonzero value through a pointer, a member or an index.",
    "A function whose only work is one call to another function of the same driver is judged by that function.",
    "A fail-safe entry of engine-ddi (FailSafe<...>) is not done. NULL is not done.",
    "A done function that also refuses some inputs with a failure constant is marked partial. Partial counts as done.",
]

# Failure constants. A return of one of these, or of an expression that names only these, is a refusal.
REFUSAL = {
    "E_NOTIMPL", "E_FAIL", "E_INVALIDARG", "E_UNEXPECTED", "E_OUTOFMEMORY", "E_NOINTERFACE", "E_POINTER",
    "DXGI_ERROR_UNSUPPORTED", "DXGI_ERROR_INVALID_CALL", "D3DDDIERR_DEVICEREMOVED",
    "STATUS_NOT_SUPPORTED", "STATUS_NOT_IMPLEMENTED", "STATUS_UNSUCCESSFUL", "STATUS_INVALID_PARAMETER",
    "STATUS_INVALID_DEVICE_REQUEST", "STATUS_NO_MEMORY", "STATUS_INSUFFICIENT_RESOURCES",
    "STATUS_INVALID_DEVICE_STATE", "STATUS_DEVICE_REMOVED", "STATUS_GRAPHICS_DRIVER_MISMATCH",
}
# A statement that names one of these is a refusal path, whatever it calls.
REFUSAL_MARKERS = {"E_NOTIMPL", "STATUS_NOT_SUPPORTED", "STATUS_NOT_IMPLEMENTED", "DXGI_ERROR_UNSUPPORTED"}
# Answers of "nothing here" in a value-returning slot.
REFUSAL_VALUE = re.compile(r"\b\w*(UNSUPPORTED|UNRECOGNIZED|NOT_SUPPORTED|NOTIMPL)\w*\b")

# Calls that are not work: logging and tracing, counters, locks, reads of state, error reports, zeroing.
NEUTRAL = {
    # logging and tracing
    "GuardLog", "GuardLogSequence", "DbgPrint", "DbgPrintEx", "KdPrint", "KdPrintEx", "WddmFirstCalls",
    "WddmTraced", "WddmAnswersLogged", "print", "flush", "log_line", "fprintf", "printf", "snprintf",
    "_snprintf", "sprintf_s", "OutputDebugStringA", "OutputDebugStringW", "trace", "ddi_trace_begin",
    "ddi_trace_end", "ddi_trace_enabled", "ddi_trace_mode", "ddi_refusal", "ddi_failure_note", "ddi_mode2_note",
    "fence_slot_seen", "QueryPerformanceCounter", "GetCurrentThreadId", "KeQueryPerformanceCounter",
    # counters
    "InterlockedIncrement", "InterlockedDecrement", "InterlockedAdd", "InterlockedIncrement64", "fetch_add",
    # the start-health record: a diagnostic state that the escape interface reports, not a device operation
    "StartHealthClose", "StartHealthEnter", "StartHealthLeave", "StartHealthFault",
    # locks
    "KeAcquireSpinLock", "KeReleaseSpinLock", "KeAcquireSpinLockAtDpcLevel", "KeReleaseSpinLockFromDpcLevel",
    "AcquireSRWLockExclusive", "ReleaseSRWLockExclusive", "AcquireSRWLockShared", "ReleaseSRWLockShared",
    "ExAcquireFastMutex", "ExReleaseFastMutex", "lock", "unlock",
    # reads of state and handle lookups
    "WddmOf", "WddmObject", "load", "KeGetCurrentIrql", "UNREFERENCED_PARAMETER", "NT_SUCCESS", "SUCCEEDED",
    "FAILED", "device_status",
    # error reports
    "report_device_error", "report_list_error", "queue_failure", "remove", "SetErrorCb", "pfnSetErrorCb",
    # zeroing
    "RtlZeroMemory", "ZeroMemory", "memset", "RtlSecureZeroMemory",
}
KEYWORDS = {
    "if", "for", "while", "switch", "return", "sizeof", "alignof", "offsetof", "static_cast", "reinterpret_cast",
    "const_cast", "dynamic_cast", "decltype", "noexcept", "defined", "__try", "__except", "__finally", "catch",
    "throw", "C_ASSERT", "static_assert", "_Analysis_assume_", "__assume", "else", "do", "case", "assert",
    # functional casts of built-in types
    "unsigned", "signed", "int", "bool", "char", "float", "double", "long", "short", "UINT", "ULONG", "DWORD",
    "BOOL", "BOOLEAN", "LONG", "UINT32", "UINT64", "ULONGLONG", "LONGLONG", "SIZE_T", "uintptr_t", "uint32_t",
    "uint64_t", "uint8_t", "uint16_t", "int32_t", "int64_t", "HRESULT", "NTSTATUS", "UINT8", "UINT16", "USHORT",
    "UCHAR", "ULONG_PTR", "size_t",
}
ZERO_VALUE = re.compile(r"^\(?\s*(0+[uUlL]*|0x0+[uUlL]*|nullptr|NULL|FALSE|false|\{\s*\}|\{\s*0\s*\}|"
                        r"[A-Za-z_][\w:<>]*\s*\{\s*\})\s*\)?$")
SUCCESS = {"S_OK", "STATUS_SUCCESS", "TRUE", "true", "S_FALSE"}


# ---- C and C++ source text -------------------------------------------------------------------------------------

def clean(text: str) -> str:
    """Comments become spaces, string and character literals become empty quotes. Line breaks stay."""
    out = []
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if text.startswith("//", i):
            j = text.find("\n", i)
            j = n if j < 0 else j
            out.append(" " * (j - i))
            i = j
        elif text.startswith("/*", i):
            j = text.find("*/", i + 2)
            j = n if j < 0 else j + 2
            out.append(re.sub(r"[^\n]", " ", text[i:j]))
            i = j
        elif c == '"' or (c == "'" and not (i and (text[i - 1].isalnum()) and i + 1 < n and text[i + 1].isdigit())):
            q = c
            j = i + 1
            while j < n and text[j] != q:
                if text[j] == "\\":
                    j += 1
                if j < n and text[j] == "\n":
                    break
                j += 1
            body = text[i + 1:j]
            out.append(q + re.sub(r"[^\n]", " ", body) + (q if j < n else ""))
            i = j + 1
        else:
            out.append(c)
            i += 1
    return "".join(out)


DEFINE = re.compile(r"^[ \t]*#[ \t]*(define|undef)[ \t]+(\w+)(\([^)]*\))?(.*)$")


def preprocess(text: str) -> str:
    """Join continuation lines (keeping the line count), blank every directive, and expand the macros that the
    file itself defines, in file order, with #undef honoured. No conditional is evaluated."""
    lines = text.split("\n")
    joined: list[str] = []
    i = 0
    while i < len(lines):
        line, extra = lines[i], 0
        while line.endswith("\\") and i + 1 < len(lines):
            i += 1
            extra += 1
            line = line[:-1] + " " + lines[i]
        joined.append(line)
        joined.extend([""] * extra)
        i += 1
    macros: dict[str, tuple[list[str] | None, str]] = {}
    out = []
    for line in joined:
        m = DEFINE.match(line)
        if m:
            if m.group(1) == "define":
                params = None
                if m.group(3) is not None:
                    params = [p.strip() for p in m.group(3)[1:-1].split(",") if p.strip()]
                macros[m.group(2)] = (params, m.group(4).strip())
            else:
                macros.pop(m.group(2), None)
            out.append("")
        elif line.lstrip().startswith("#"):
            out.append("")
        else:
            out.append(expand(line, macros))
    return "\n".join(out)


def split_args(text: str) -> list[str]:
    args, depth, cur = [], 0, []
    for ch in text:
        if ch in "([{<" and ch != "<":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        if ch == "," and depth == 0:
            args.append("".join(cur).strip())
            cur = []
        else:
            cur.append(ch)
    args.append("".join(cur).strip())
    return args


def match_paren(text: str, i: int) -> int:
    """Index of the bracket that closes text[i], or -1."""
    pairs = {"(": ")", "{": "}", "[": "]"}
    want = [pairs[text[i]]]
    j = i + 1
    while j < len(text):
        ch = text[j]
        if ch in pairs:
            want.append(pairs[ch])
        elif ch in ")}]":
            if not want or ch != want[-1]:
                return -1
            want.pop()
            if not want:
                return j
        j += 1
    return -1


IDENT = re.compile(r"[A-Za-z_]\w*")


def expand(line: str, macros: dict, depth: int = 0) -> str:
    if depth > 8 or not macros:
        return line
    out, i, changed = [], 0, False
    while i < len(line):
        m = IDENT.match(line, i)
        if not m or (i and (line[i - 1].isalnum() or line[i - 1] == "_")):
            out.append(line[i])
            i += 1
            continue
        name = m.group(0)
        j = m.end()
        if name in macros:
            params, body = macros[name]
            if params is None:
                out.append(body)
                i = j
                changed = True
                continue
            k = j
            while k < len(line) and line[k] in " \t":
                k += 1
            if k < len(line) and line[k] == "(":
                e = match_paren(line, k)
                if e > 0:
                    args = split_args(line[k + 1:e])
                    out.append(substitute(params, body, args))
                    i = e + 1
                    changed = True
                    continue
        out.append(name)
        i = j
    text = "".join(out)
    return expand(text, macros, depth + 1) if changed else text


def substitute(params: list[str], body: str, args: list[str]) -> str:
    values = dict(zip(params, args + [""] * (len(params) - len(args))))
    body = re.sub(r"#\s*(\w+)", lambda m: '"' + values.get(m.group(1), m.group(1)) + '"'
                  if m.group(1) in values else m.group(0), body.replace("##", "\x00"))
    body = re.sub(r"\b\w+\b", lambda m: values.get(m.group(0), m.group(0)), body)
    return re.sub(r"\s*\x00\s*", "", body)


class Source:
    """One source file, cleaned and preprocessed, with line numbers kept."""

    def __init__(self, path: Path, text: str | None = None):
        self.path = path
        self.rel = path.relative_to(REPO).as_posix() if text is None else path.as_posix()
        raw = path.read_text(encoding="utf-8", errors="replace") if text is None else text
        self.text = preprocess(clean(raw))
        self._starts = [0] + [m.end() for m in re.finditer("\n", self.text)]

    def line(self, pos: int) -> int:
        lo, hi = 0, len(self._starts) - 1
        while lo < hi:
            mid = (lo + hi + 1) // 2
            if self._starts[mid] <= pos:
                lo = mid
            else:
                hi = mid - 1
        return lo + 1


class Function:
    def __init__(self, name, src: Source, pos, ret, body, params):
        self.name, self.src, self.pos, self.ret, self.body, self.params = name, src, pos, ret, body, params

    @property
    def where(self) -> str:
        return f"{self.src.rel}:{self.src.line(self.pos)}"


NOT_RET = {"return", "else", "new", "delete", "case", "throw", "co_return", "goto"}


def find_functions(src: Source) -> dict[str, list[Function]]:
    """Every function definition: a name, a parameter list, qualifiers, then a body."""
    found: dict[str, list[Function]] = {}
    text = src.text
    for m in re.finditer(r"\b([A-Za-z_]\w*)\s*\(", text):
        name = m.group(1)
        if name in KEYWORDS or name in NOT_RET:
            continue
        before = text[:m.start()].rstrip()
        if not before or before[-1] in "=(,.!&|?:+-/%^~<[" and not before.endswith("::"):
            if not before.endswith("*") and not before.endswith("&") and not before.endswith(">"):
                continue
        if before.endswith("->") or (before.endswith(".") and not before.endswith("..")):
            continue
        prev = re.search(r"([A-Za-z_]\w*)\s*$", before)
        if prev and prev.group(1) in NOT_RET:
            continue
        if not prev and not before.endswith(("*", "&", ">", "::")):
            continue
        open_ = m.end() - 1
        close = match_paren(text, open_)
        if close < 0:
            continue
        k = close + 1
        tail = re.match(r"(\s*(noexcept(\s*\([^)]*\))?|const|override|final|throw\s*\(\s*\)|->\s*[\w:<>*&\s]+?))*\s*\{",
                        text[k:])
        if not tail:
            continue
        b = k + tail.end() - 1
        e = match_paren(text, b)
        if e < 0:
            continue
        start = max(text.rfind(";", 0, m.start()), text.rfind("}", 0, m.start()), text.rfind("{", 0, m.start()))
        ret = " ".join(text[start + 1:m.start()].split())
        ret = re.sub(r"\btemplate\s*<.*?>\s*", "", ret)
        if re.search(r"\b(if|while|for|switch|return)\b", ret) or "=" in ret:
            continue
        found.setdefault(name, []).append(Function(name, src, m.start(), ret, text[b + 1:e], text[open_ + 1:close]))
    return found


# ---- the verdict ---------------------------------------------------------------------------------------------------

def statements(body: str) -> list[str]:
    """Split a body into statements at top-level ';', '{' and '}'. Parentheses keep lambdas inside a call."""
    out, depth, cur = [], 0, []
    for ch in body:
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        if depth == 0 and ch in ";{}":
            s = "".join(cur).strip()
            if s:
                out.append(s)
            cur = []
        else:
            cur.append(ch)
    s = "".join(cur).strip()
    if s:
        out.append(s)
    return out


HEADER = re.compile(r"^\s*(?:else\b|do\b|try\b|__try\b|default\s*:|case\b[^:]*:(?!:)|"
                    r"(?:if|while|for|switch|__except|catch)\s*(?=\())")


def strip_headers(stmt: str) -> tuple[str, list[str]]:
    """Remove leading control headers and return the core statement and the header conditions."""
    conds = []
    while True:
        m = HEADER.match(stmt)
        if not m:
            break
        rest = stmt[m.end():]
        if rest.lstrip().startswith("(") and m.group(0).strip()[:2] in ("if", "wh", "fo", "sw", "__", "ca"):
            k = len(rest) - len(rest.lstrip())
            e = match_paren(rest, k)
            if e < 0:
                break
            conds.append(rest[k + 1:e])
            stmt = rest[e + 1:]
        else:
            stmt = rest
    return stmt.strip(), conds


CALL = re.compile(r"(?<![\w.])((?:[A-Za-z_]\w*\s*(?:::|\.|->)\s*)*)([A-Za-z_]\w*)\s*(?:<[^<>;()]*>)?\s*\(")


def calls_in(text: str) -> list[str]:
    return [m.group(2) for m in CALL.finditer(text) if m.group(2) not in KEYWORDS]


def top_level_assign(stmt: str) -> tuple[str, str] | None:
    depth = 0
    for i, ch in enumerate(stmt):
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        elif ch == "=" and depth == 0:
            if stmt[i + 1:i + 2] == "=" or stmt[i - 1:i] in ("=", "!", "<", ">"):
                continue
            lhs = stmt[:i]
            if lhs and lhs[-1] in "+-*/|&^%<>":
                lhs = lhs[:-1]
            return lhs.strip(), stmt[i + 1:].strip()
    return None


def is_declaration(lhs: str) -> bool:
    return bool(re.match(r"^(?:const\s+|static\s+|volatile\s+|auto\s*)*[\w:<>,\s]*?[\w>]\s*[\s*&]+\s*\w+(\[\w*\])?$",
                         lhs)) and not re.search(r"->|\.", lhs) and not lhs.startswith("*")


def is_write(lhs: str) -> bool:
    if is_declaration(lhs):
        return False
    return bool(re.search(r"->|\.|\[|^\s*\*|^\s*\(\s*\*", lhs))


FAILURE_NAME = re.compile(r"^(STATUS_(?!SUCCESS$|PENDING$|MORE_PROCESSING_REQUIRED$)\w+|E_\w+|DXGI_ERROR_\w+|"
                          r"D3DDDIERR_\w+)$")


def ternary(expr: str) -> tuple[str, str] | None:
    """The two results of a top-level 'cond ? a : b', or None."""
    depth, q = 0, -1
    for i, ch in enumerate(expr):
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        elif depth == 0 and ch == "?" and q < 0:
            q = i
        elif depth == 0 and ch == ":" and q >= 0 and expr[i - 1:i + 1] != "::" and expr[i:i + 2] != "::":
            return expr[q + 1:i].strip(), expr[i + 1:].strip()
    return None


def is_failure(expr: str) -> bool:
    """True when the expression names failure constants and nothing else. For a ternary, both results."""
    expr = expr.strip()
    while expr.startswith("(") and match_paren(expr, 0) == len(expr) - 1:
        expr = expr[1:-1].strip()
    t = ternary(expr)
    if t:
        return is_failure(t[0]) and is_failure(t[1])
    words = re.findall(r"[A-Za-z_]\w*", expr)
    rest = re.sub(r"[\s(),]|[A-Za-z_]\w*", "", expr)
    return bool(words) and not rest and all(w in REFUSAL or FAILURE_NAME.match(w) for w in words)


def fn_kind(fn: "Function") -> str:
    ret = fn.ret
    return ("void" if re.search(r"\b(void|VOID)\b", ret) and "*" not in ret else
            "status" if re.search(r"\b(HRESULT|NTSTATUS)\b", ret) else "value")


class Judge:
    def __init__(self, index: dict[str, list[Function]]):
        self.index = index
        self._work: dict[str, bool] = {}

    def resolve(self, name: str, near: Source | None = None) -> tuple[Function | None, bool]:
        defs = self.index.get(name, [])
        if not defs:
            return None, False
        if near:
            same = [d for d in defs if d.src is near]
            if same:
                return same[0], len(same) > 1 and len({d.body for d in same}) > 1
        return defs[0], len({(d.src.rel, d.body) for d in defs}) > 1

    def analyze(self, fn: Function) -> dict:
        work_calls, writes, refusals, returns, calls = [], 0, 0, [], []
        for raw in statements(fn.body):
            core, conds = strip_headers(raw)
            for c in conds:
                work_calls += [x for x in self.note(calls_in(c), calls) if self.call_is_work(x, fn.src)]
                a = top_level_assign(c)
                if a and is_write(a[0]):
                    writes += 1
            if not core:
                continue
            if re.search(r"\b(new|delete)\b|(->|\.)\s*~\w", core):
                writes += 1         # an object is built or destroyed
            if re.match(r"^return\b", core):
                expr = core[6:].strip()
                returns.append(expr)
                work_calls += [x for x in self.note(calls_in(expr), calls) if self.call_is_work(x, fn.src)]
                continue
            if any(re.search(r"\b" + r + r"\b", core) for r in REFUSAL_MARKERS):
                refusals += 1
                continue
            first = CALL.match(core)
            if first and first.start() == 0 and first.group(2) in NEUTRAL and not top_level_assign(core):
                continue
            if re.match(r"^\(void\)\s*", core):
                core = re.sub(r"^\(void\)\s*", "", core)
                first = CALL.match(core)
                if first and first.group(2) in NEUTRAL:
                    continue
            a = top_level_assign(core)
            if a:
                lhs, rhs = a
                if is_write(lhs) and not ZERO_VALUE.match(rhs):
                    writes += 1
                work_calls += [x for x in self.note(calls_in(rhs), calls) if self.call_is_work(x, fn.src)]
                if is_declaration(lhs) and "(" in lhs:
                    work_calls += [x for x in self.note(calls_in(lhs), calls) if self.call_is_work(x, fn.src)]
                continue
            work_calls += [x for x in self.note(calls_in(core), calls) if self.call_is_work(x, fn.src)]
        return {"work_calls": work_calls, "writes": writes, "refusals": refusals, "returns": returns,
                "calls": sorted(set(calls))}

    def note(self, names: list[str], into: list[str]) -> list[str]:
        into += [n for n in names if n not in NEUTRAL]
        return names

    def call_is_work(self, name: str, near: Source) -> bool:
        if name in NEUTRAL or name in KEYWORDS:
            return False
        if name in self._work:
            return self._work[name]
        fn, _ = self.resolve(name, near)
        if fn is None:
            return True
        self._work[name] = True        # recursion guard: a cycle counts as work
        a = self.analyze(fn)
        result = bool(a["work_calls"] or a["writes"])
        self._work[name] = result
        return result

    def verdict(self, name: str, near: Source, depth: int = 0) -> dict:
        fn, ambiguous = self.resolve(name, near)
        if fn is None:
            return {"function": name, "done": False, "reason": "no definition in the driver source", "source": None}
        a = self.analyze(fn)
        kind = fn_kind(fn)
        base = {"function": name, "source": fn.where}
        if ambiguous:
            base["ambiguous"] = True
        exprs = [r for r in a["returns"] if r]
        if exprs and all(self.fails(r, fn.src) for r in exprs) and kind != "void":
            return {**base, "done": False, "reason": "every return is a failure constant"}
        if kind == "value":
            if exprs and all(REFUSAL_VALUE.search(r) and not calls_in(r) for r in exprs):
                return {**base, "done": False, "reason": "every return is a 'not supported' answer"}
            return {**base, "done": True, "reason": "returns the answer",
                    **({"partial": True} if a["refusals"] else {})}
        work = a["work_calls"]
        # A forwarder: its one call outside NEUTRAL goes to a function of the same driver, and it writes nothing.
        if not a["writes"] and depth < 4 and len(a["calls"]) == 1 and a["calls"][0] != name:
            inner, _ = self.resolve(a["calls"][0], fn.src)
            if inner is not None and fn_kind(inner) != "value":
                bound = self.constant_refusal(fn, inner)
                if bound:
                    return {**base, "done": False,
                            "reason": f"forwards to {inner.name} with {bound}"}
                v = self.verdict(a["calls"][0], fn.src, depth + 1)
                return {**base, "done": v["done"], "reason": f"forwards to {a['calls'][0]}: {v['reason']}",
                        **({"partial": True} if v.get("partial") else {})}
        if not work and not a["writes"]:
            why = "refuses every call" if a["refusals"] else "only logs, counts, reads or writes zeros"
            return {**base, "done": False, "reason": why}
        partial = a["refusals"] > 0 or any(m in r for r in exprs for m in REFUSAL_MARKERS)
        return {**base, "done": True, "reason": "does work", **({"partial": True} if partial else {})}

    @staticmethod
    def param_names(fn: Function) -> list[str]:
        names = []
        for p in split_args(fn.params):
            p = p.split("=")[0].strip()
            m = re.search(r"(\w+)\s*(\[\w*\])?$", p)
            names.append(m.group(1) if m and p not in ("void", "") else "")
        return names

    def bindings(self, caller: Function, callee: Function, given: dict[str, str]) -> dict[str, str]:
        """Parameters of callee that a call in caller sets to a constant, or to a parameter already bound."""
        out = {}
        params = self.param_names(callee)
        for m in re.finditer(r"\b" + re.escape(callee.name) + r"\s*\(", caller.body):
            e = match_paren(caller.body, m.end() - 1)
            if e < 0:
                continue
            for k, arg in enumerate(split_args(caller.body[m.end():e])):
                if k >= len(params) or not params[k]:
                    continue
                if arg in given:
                    out[params[k]] = given[arg]
                elif re.fullmatch(r"\w+::\w+|[A-Z][A-Z0-9_]{2,}", arg):
                    out[params[k]] = arg
        return out

    def constant_refusal(self, caller: Function, callee: Function, given: dict | None = None, depth: int = 0) -> str:
        """A forwarder that passes a constant which a branch of the callee (or of a function it passes the value
        on to) answers with a refusal marker and a return: the constant, or ''."""
        bound = self.bindings(caller, callee, given or {})
        if not bound or depth > 3:
            return ""
        for param, const in bound.items():
            pat = (r"\bif\s*\(\s*" + re.escape(param) + r"\s*==\s*" + re.escape(const) + r"\s*\)\s*(\{[^{}]*\}|[^;]*;)")
            for m in re.finditer(pat, callee.body):
                block = m.group(1)
                if re.search(r"\breturn\b", block) and any(re.search(r"\b" + r + r"\b", block) for r in REFUSAL_MARKERS):
                    return f"{const}, which {callee.name} refuses"
        for name in set(calls_in(callee.body)):
            inner, _ = self.resolve(name, callee.src)
            if inner is not None and inner is not callee:
                found = self.constant_refusal(callee, inner, bound, depth + 1)
                if found:
                    return found
        return ""

    def fails(self, expr: str, near: Source, depth: int = 0) -> bool:
        """A return expression that can only be a failure: failure constants, or a call to a status function of
        the same driver whose every return fails."""
        expr = expr.strip()
        while expr.startswith("(") and match_paren(expr, 0) == len(expr) - 1:
            expr = expr[1:-1].strip()
        t = ternary(expr)
        if t:
            return self.fails(t[0], near, depth) and self.fails(t[1], near, depth)
        if is_failure(expr):
            return True
        m = re.match(r"^(?:\w+\s*(?:::|\.|->)\s*)*(\w+)\s*\(", expr)
        if not m or depth > 3 or match_paren(expr, m.end() - 1) != len(expr) - 1:
            return False
        fn, _ = self.resolve(m.group(1), near)
        if fn is None or fn_kind(fn) != "status":
            return False
        rets = [r for r in self.analyze(fn)["returns"] if r]
        return bool(rets) and all(self.fails(r, fn.src, depth + 1) for r in rets)


def load_sources(dirs: list[Path], exclude: re.Pattern) -> tuple[list[Source], dict[str, list[Function]]]:
    sources, index = [], {}
    for d in dirs:
        for p in sorted(d.iterdir()):
            if p.suffix in (".c", ".cpp", ".h") and not exclude.search(p.name):
                s = Source(p)
                sources.append(s)
                for k, v in find_functions(s).items():
                    index.setdefault(k, []).extend(v)
    return sources, index


def body_of(index, name: str, rel: str) -> Function:
    for f in index.get(name, []):
        if f.src.rel == rel:
            return f
    raise SystemExit(f"status_map: {name} not found in {rel}; the source layout changed, update this script")


# ---- WDK structures ------------------------------------------------------------------------------------------------

def find_header(kits: Path, rel: str) -> Path:
    hits = sorted(kits.rglob(f"Include/{WDK_VERSION}/{rel}"))
    if not hits:
        raise SystemExit(f"status_map: {rel} of WDK {WDK_VERSION} not found under the --kits directory")
    return hits[0]


def struct_members(text: str, name: str) -> list[dict]:
    """Members of 'typedef struct NAME { ... }' in order, each with its type and the interface-version guard."""
    m = re.search(r"typedef\s+struct\s+_?" + re.escape(name) + r"\b[^{;]*\{", text)
    if not m:
        raise SystemExit(f"status_map: struct {name} not found in the WDK header")
    e = match_paren(text, m.end() - 1)
    members, guards = [], []
    for line in text[m.end():e].split("\n"):
        s = line.strip()
        g = re.match(r"#\s*if\s*\(?\s*DXGKDDI_INTERFACE_VERSION\s*>=\s*DXGKDDI_INTERFACE_VERSION_(\w+)", s)
        if g:
            guards.append(g.group(1))
            continue
        if s.startswith("#if"):
            guards.append(None)
            continue
        if s.startswith("#endif"):
            if guards:
                guards.pop()
            continue
        mm = re.match(r"^([A-Za-z_][\w\s*]*?)\s*\b([A-Za-z_]\w*)\s*;", s)
        if mm:
            typ = " ".join(mm.group(1).split())
            since = next((x for x in reversed(guards) if x), None)
            members.append({"name": mm.group(2), "type": typ, "since": since})
    return members


def is_slot(member: dict) -> bool:
    return not re.fullmatch(r"(PVOID|VOID\s*\*|void\s*\*|ULONG|UINT|SIZE_T)", member["type"].replace(" *", "*")
                            .replace("* ", "*").replace("VOID*", "VOID *").replace("void*", "void *"))


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


# ---- metric 1: the kernel-mode DDI ---------------------------------------------------------------------------------

KMD_FAMILIES = [
    ("Recovery and diagnostics", r"Timeout|CollectDbgInfo|DependentEngineGroup|EngineStatus|ResetEngine|ResetHwEngine|"
                                 r"ResumeHwEngine|CancelCommand|Diagnostic|ResetDisplayEngine|NotifySurpriseRemoval"),
    ("Virtualization", r"VirtualMachine|Migration|VirtualGpu|VirtualFunction|VirtualizedInterrupt|ExclusiveAccess|"
                       r"DirtyTracking|DirtyBitData|HotUpdate"),
    ("Content protection", r"Protected|AnalogCopyProtection"),
    ("Interrupt", r"Interrupt|DpcRoutine"),
    ("Present and flip", r"Present|SetVidPnSourceAddress|Overlay|MultiPlane|FlipQueue|QueuedFlips|CancelFlips|"
                         r"PeriodicFrameNotification|DisplayPrivateDriverFormat|PostCompositionCaps"),
    ("Display and VidPN", r"Child|DeviceDescriptor|VidPn|MonitorModes|MonitorLinkInfo|ScanLine|Timings|Target|"
                          r"DisplayDetect|ConnectionChange|ModeBehavior|SystemDisplay|Palette|Pointer|StopCapture|"
                          r"ExchangePreStartInfo"),
    ("Memory and paging", r"Allocation|Swizzling|Patch$|PagingBuffer|PageTable|PageDirectory|CpuHostAperture|"
                          r"MemoryBasis|BackingStore"),
    ("Scheduling and submission", r"MonitoredValues|CurrentValues|CreateDevice|DestroyDevice|Context|Process|SubmitCommand|Preempt|Render|"
                                  r"CurrentFence|NodeMetadata|HwQueue|HwContext|Scheduling|PriorityBands|Fence|"
                                  r"Doorbell|WorkSubmission|CpuEvent|CalibrateGpuClock|HistoryBuffer|"
                                  r"TrackedWorkload|FocusPresent|LinkDevice"),
    ("Device and power", r"."),
]


def version_label(name: str) -> str:
    """WDDM2_9 -> WDDM 2.9, WIN8 -> WIN8."""
    m = re.fullmatch(r"WDDM(\d+(?:_\d+)*)", name)
    return f"WDDM {m.group(1).replace('_', '.')}" if m else name


def kmd_family(name: str) -> str:
    short = name.replace("DxgkDdi", "", 1)
    for family, pattern in KMD_FAMILIES:
        if re.search(pattern, short):
            return family
    return KMD_FAMILIES[-1][0]


def kmd_metric(kits: Path | None, prior: dict | None) -> dict:
    if kits:
        header = find_header(kits, KMD_HEADER)
        members = struct_members(header.read_text(encoding="utf-8", errors="replace"), "DRIVER_INITIALIZATION_DATA")
        slots = [{"name": m["name"], "since": m["since"]} for m in members if m["name"].startswith("DxgkDdi")
                 and is_slot(m)]
        taken = {s["name"] for s in slots}
        reserved = [m["name"] for m in members if m["name"] != "Version" and m["name"] not in taken]
        header_info = {"wdk": WDK_VERSION, "file": KMD_HEADER, "sha256": sha256(header),
                       "struct": "DRIVER_INITIALIZATION_DATA"}
        vheader = find_header(kits, VERSION_HEADER)
        versions = {k: int(v, 16) for k, v in re.findall(
            r"#define\s+DXGKDDI_INTERFACE_VERSION_(\w+)\s+0x([0-9A-Fa-f]+)", vheader.read_text(encoding="utf-8",
                                                                                           errors="replace"))}
        version_info = {"file": VERSION_HEADER, "sha256": sha256(vheader), "values": versions}
    else:
        slots = [{"name": s["name"], "since": s.get("since")} for g in prior["groups"] for s in g["slots"]]
        reserved = prior["reserved"]
        header_info = prior["header"]
        version_info = prior["interface_versions"]
    kmd = REPO / "driver" / "kmd"
    sources, index = load_sources([kmd], re.compile(r"(^test_|_test\.|probe)"))
    build = body_of(index, "WddmBuildTable", "driver/kmd/wddm.c")
    assigned = dict(re.findall(r"\bData\s*->\s*(DxgkDdi\w+)\s*=\s*([A-Za-z_]\w*)\s*;", build.body))
    judge = Judge(index)
    declared = re.search(r"Data->Version\s*=\s*DXGKDDI_INTERFACE_VERSION_(\w+)", build.body).group(1)
    values = version_info["values"]
    missing = sorted({s["since"] for s in slots if s["since"]} - set(values)) + ([declared] if declared not in values
                                                                                else [])
    if missing:
        raise SystemExit(f"status_map: no value for interface versions {missing} in {VERSION_HEADER}")
    names = {s["name"] for s in slots}
    unknown = sorted(set(assigned) - names)
    if unknown:
        raise SystemExit(f"status_map: WddmBuildTable sets members the header lacks: {unknown}")
    groups: dict[str, list] = {}
    for s in slots:
        entry = {"name": s["name"], "since": s["since"],
                 "targeted": s["since"] is None or values[s["since"]] <= values[declared]}
        if s["name"] in assigned:
            entry.update(judge.verdict(assigned[s["name"]], build.src))
        else:
            entry.update({"function": None, "done": False, "reason": "NULL in WddmBuildTable", "source": None})
        groups.setdefault(kmd_family(s["name"]), []).append(entry)
    return {
        "id": "kmd-ddi",
        "title": "Kernel-mode DDI",
        "header": header_info,
        "table": "WddmBuildTable in driver/kmd/wddm.c (the full WDDM table)",
        "declared_version": "DXGKDDI_INTERFACE_VERSION_" + declared,
        "declared_label": version_label(declared),
        "interface_versions": version_info,
        "reserved": reserved,
        "groups": [{"name": k, "slots": v} for k, v in groups.items()],
    }


# ---- metric 2: the D3D12 user-mode DDI ------------------------------------------------------------------------------

def umd_metric(kits: Path | None, prior: dict | None) -> dict:
    d12 = REPO / "driver" / "umd" / "d3d12"
    sources, index = load_sources([d12, d12 / "engine-ddi"], re.compile(r"(-test\.cpp$|-probe\.cpp$|^harness)"))
    judge = Judge(index)
    fill = body_of(index, "fill_native_tables", "driver/umd/d3d12/native-tables.cpp")
    adapter_src = next(s for s in sources if s.rel.endswith("/adapter.cpp"))
    build = re.search(r"D3D12DDI_SUPPORTED_(\d{4})", adapter_src.text).group(1)
    case_type = {}
    for m in re.finditer(r"case\s+(D3D12DDI_TABLE_TYPE_\w+)\s*:\s*\{(.*?)(?=case\s+D3D12DDI_TABLE_TYPE_|default\s*:)",
                         fill.body, re.S):
        t = re.search(r"\b(?:using\s+\w+\s*=\s*)?(D3D12DDI_\w+_FUNCS_\w+)\b", m.group(2))
        case_type[m.group(1)] = t.group(1) if t else None
    aliases = dict(re.findall(r"using\s+(\w+)\s*=\s*(D3D12DDI_\w+)\s*;", fill.src.text))
    for k, v in case_type.items():
        if v is None:
            body = re.search(r"case\s+" + k + r"\s*:\s*\{(.*?)\n\s*\}", fill.body, re.S).group(1)
            alias = re.search(r"sizeof\((\w+)\)", body).group(1)
            case_type[k] = aliases[alias]
    adapter_struct = "D3D12DDI_ADAPTERFUNCS"
    tables = [("Adapter", adapter_struct, None)] + [
        (label, case_type[t], t) for label, t in (
            ("Device core", "D3D12DDI_TABLE_TYPE_DEVICE_CORE"),
            ("Command list", "D3D12DDI_TABLE_TYPE_COMMAND_LIST_3D"),
            ("Command queue", "D3D12DDI_TABLE_TYPE_COMMAND_QUEUE_3D"),
            ("Extended features", "D3D12DDI_TABLE_TYPE_0020_EXTENDED_FEATURES"))]
    missing = sorted(set(case_type) - {t for _, _, t in tables})
    if missing:
        raise SystemExit(f"status_map: fill_native_tables publishes tables this script does not count: {missing}")
    if kits:
        header = find_header(kits, UMD_HEADER)
        htext = header.read_text(encoding="utf-8", errors="replace")
        layouts = {s: struct_members(htext, s) for _, s, _ in tables}
        header_info = {"wdk": WDK_VERSION, "file": UMD_HEADER, "sha256": sha256(header)}
    else:
        layouts = {g["struct"]: g["layout"] for g in prior["groups"]}
        header_info = prior["header"]

    # Assignments, in the order the driver makes them. Each list is (member, function, source Function).
    def scan(fn: Function, table_var: str, seen=None) -> list[tuple[str, str, Function]]:
        seen = seen or set()
        out = []
        pat = re.compile(r"(?:\b" + table_var + r"\s*(?:->|\.)|\(\s*" + table_var + r"\s*\)\s*->)\s*(pfn\w+)\s*=\s*"
                         r"([^;]+);|\b([a-z_]\w*)\s*\(\s*&?\s*" + table_var + r"\b")
        for m in pat.finditer(fn.body):
            if m.group(1):
                out.append((m.group(1), m.group(2).strip(), fn))
            else:
                callee = m.group(3)
                if callee in seen or callee in KEYWORDS:
                    continue
                inner, _ = judge.resolve(callee, fn.src)
                if inner is None or "pfn" not in inner.body:
                    continue
                params = [p.strip() for p in split_args(inner.params) if p.strip()]
                pname = re.search(r"(\w+)\s*$", params[0]).group(1) if params else table_var
                out += scan(inner, pname, seen | {callee})
        return out

    def rhs_function(rhs: str) -> str:
        if rhs.startswith("FailSafe<") or "FailSafe<" in rhs.split("?")[-1]:
            return "FailSafe"
        m = re.match(r"&?\s*([A-Za-z_][\w:]*)\s*$", rhs)
        return m.group(1).split("::")[-1] if m else rhs

    def judge_slot(func: str, src: Function, wrapped: dict | None = None) -> dict:
        if func == "FailSafe":
            return {"function": "FailSafe", "done": False, "reason": "fail-safe entry of engine-ddi",
                    "source": src.where}
        v = judge.verdict(func, src.src)
        if wrapped is not None and not wrapped["done"]:
            return {**v, "done": False, "reason": f"wraps {wrapped['function']}: {wrapped['reason']}"}
        return v

    groups = []
    # The adapter table: the aggregate that OpenAdapter12 stores.
    open_adapter = body_of(index, "OpenAdapter12", "driver/umd/d3d12/adapter.cpp")
    agg = re.search(r"\*\s*a\s*->\s*pAdapterFuncs\s*=\s*\{([^{}]+)\}", open_adapter.body).group(1)
    per_table: dict[str, dict[str, tuple[str, Function]]] = {"Adapter": {}}
    slots_adapter = [m for m in layouts[adapter_struct] if is_slot(m)]
    for member, func in zip(layouts[adapter_struct], [x.strip() for x in split_args(agg)]):
        per_table["Adapter"][member["name"]] = (func, open_adapter)
    # Device core: engine fill (fail-safe, then the engine modules), the shell's slots, then the wrapped resources.
    core_case = re.search(r"case\s+D3D12DDI_TABLE_TYPE_DEVICE_CORE\s*:\s*\{(.*?)\n\s{4}\}", fill.body, re.S).group(1)
    engine_core = body_of(index, "fill_device_core", "driver/umd/d3d12/engine-ddi/context.cpp")
    core: dict[str, tuple[str, Function]] = {}
    for member, rhs, f in scan(engine_core, "table"):
        core[member] = (rhs_function(rhs), f)
    shell_fn = Function("fill_native_tables", fill.src, fill.pos, "", core_case.split("compose_core_0092")[0], "")
    for member, rhs, f in scan(shell_fn, "shell"):
        core[member] = (rhs_function(rhs), f if f is not shell_fn else fill)
    wraps = {}
    for m in re.finditer(r"\boriginal\.(pfn\w+)\s*=\s*(\w+)\s*;", core_case):
        if re.search(r"store\(\s*original\." + m.group(1) + r"\s*\)", core_case):
            wraps[m.group(1)] = core.get(m.group(1))
        core[m.group(1)] = (m.group(2), fill)
    per_table["Device core"] = core
    # Command list: the engine fill for table 1 (graphics), then the shell's Present.
    engine_list = body_of(index, "fill_command_list", "driver/umd/d3d12/engine-ddi/context.cpp")
    lst = {}
    for member, rhs, f in scan(engine_list, "table"):
        lst[member] = (rhs_function(rhs), f)
    compose = body_of(index, "compose_list_0092", "driver/umd/d3d12/device-table.h")
    present_arg = re.search(r"compose_list_0092\s*\(([^;]*)\)\s*;", fill.body)
    lst["pfnPresent"] = (split_args(present_arg.group(1))[3].strip(), fill)
    assert "candidate.pfnPresent = present" in " ".join(compose.body.split())
    per_table["Command list"] = lst
    # Command queue and extended features: the shell's fill functions behind the wrapping thunks.
    queue_fill = body_of(index, "fill_native_queue_table", "driver/umd/d3d12/native-queue-ddi.cpp")
    per_table["Command queue"] = {m: (rhs_function(r), f) for m, r, f in scan(queue_fill, "candidate")}
    ext_fill = body_of(index, "fill_native_extended_table", "driver/umd/d3d12/native-queue-ddi.cpp")
    ext_agg = re.search(r"\*\s*output\s*=\s*\{([^{}]+)\}", ext_fill.body).group(1)
    per_table["Extended features"] = {}
    ext_struct = case_type["D3D12DDI_TABLE_TYPE_0020_EXTENDED_FEATURES"]
    for member, func in zip(layouts[ext_struct], [x.strip() for x in split_args(ext_agg)]):
        per_table["Extended features"][member["name"]] = (func, ext_fill)

    for label, struct, _ in tables:
        layout = layouts[struct]
        assigned = per_table[label]
        unknown = sorted(set(assigned) - {m["name"] for m in layout})
        if unknown:
            raise SystemExit(f"status_map: the {label} table sets members that {struct} lacks: {unknown}")
        entries = []
        for m in layout:
            if not is_slot(m):
                continue
            if m["name"] in assigned:
                func, src = assigned[m["name"]]
                wrapped = None
                if label == "Device core" and m["name"] in wraps and wraps[m["name"]]:
                    wf, ws = wraps[m["name"]]
                    wrapped = judge_slot(wf, ws)
                entry = {"name": m["name"], **judge_slot(func, src, wrapped)}
            else:
                entry = {"name": m["name"], "function": None, "done": False, "reason": "NULL", "source": None}
            entries.append(entry)
        groups.append({"name": label, "struct": struct, "layout": layout, "slots": entries})
    return {
        "id": "d3d12-ddi",
        "title": "D3D12 user-mode DDI",
        "header": header_info,
        "build": build,
        "table": "OpenAdapter12 and fill_native_tables in driver/umd/d3d12 (the command-list slots of table 1, "
                 "the graphics table)",
        "groups": groups,
    }


# ---- squarified treemap and SVG --------------------------------------------------------------------------------------

def squarify(values: list[float], x: float, y: float, w: float, h: float) -> list[tuple[float, float, float, float]]:
    """Bruls, Huizing and van Wijk (2000). values sorted descending, positive. Returns one rectangle per value."""
    total = sum(values)
    scale = w * h / total
    areas = [v * scale for v in values]
    rects: list = []
    row: list[float] = []

    def worst(r, side):
        s = sum(r)
        return max(side * side * max(r) / (s * s), s * s / (side * side * min(r)))

    def lay(r):
        nonlocal x, y, w, h
        s = sum(r)
        if w >= h:
            cw = s / h
            yy = y
            for a in r:
                rects.append((x, yy, cw, a / cw))
                yy += a / cw
            x += cw
            w -= cw
        else:
            ch = s / w
            xx = x
            for a in r:
                rects.append((xx, y, a / ch, ch))
                xx += a / ch
            y += ch
            h -= ch

    i = 0
    while i < len(areas):
        side = min(w, h)
        a = areas[i]
        if not row or worst(row + [a], side) <= worst(row, side):
            row.append(a)
            i += 1
        else:
            lay(row)
            row = []
    if row:
        lay(row)
    return rects


THEME = {"bg": "#0d1117", "panel": "#161b22", "border": "#30363d", "text": "#e6edf3", "muted": "#9198a1",
         "done": "#2ea043", "partial": "#2ea043", "missing": "#3d444d", "halo": "#0d1117"}
FONT = "-apple-system,BlinkMacSystemFont,'Segoe UI','Noto Sans',Helvetica,Arial,sans-serif"


def text_width(s: str, size: float) -> float:
    w = 0.0
    for ch in s:
        w += (0.33 if ch in "il.,:;'|!" else 0.3 if ch == " " else 0.62 if ch.isupper() or ch.isdigit()
              else 0.85 if ch in "mwMW%" else 0.53) * size
    return w


def fmt(v: float) -> str:
    s = f"{v:.2f}"
    return s.rstrip("0").rstrip(".") if "." in s else s


def pct(done: int, total: int) -> str:
    return f"{100.0 * done / total:.2f}%" if total else "n/a"


def treemap_svg(metric: dict, width: int = 860, map_h: int = 330) -> str:
    groups = [g for g in metric["groups"] if g["slots"]]
    groups.sort(key=lambda g: (-len(g["slots"]), g["name"]))
    done, total, _ = counts(metric)
    newer = sum(not targeted(s) for g in groups for s in g["slots"])
    newer_text = f'newer than {metric.get("declared_label", "")} (not targeted yet)'
    pad, head = 10, 46
    mx, my, mw = pad, head, width - 2 * pad
    rects = squarify([len(g["slots"]) for g in groups], mx, my, mw, map_h)
    parts = []
    hidden = []
    for g, (x, y, w, h) in zip(groups, rects):
        # The frame has the colour of the card, so the free area after the last cell reads as no cell at all.
        parts.append(f'<rect x="{fmt(x + 1.5)}" y="{fmt(y + 1.5)}" width="{fmt(w - 3)}" height="{fmt(h - 3)}" '
                     f'rx="3" fill="{THEME["panel"]}" stroke="{THEME["border"]}"/>')
        gx, gy, gw, gh = x + 3.5, y + 3.5, w - 7, h - 7
        n = len(g["slots"])
        best = None
        for cols in range(1, n + 1):
            rows = math.ceil(n / cols)
            cw, ch = gw / cols, gh / rows
            score = max(cw / ch, ch / cw) + 0.02 * (cols * rows - n)
            if best is None or score < best[0]:
                best = (score, cols, rows, cw, ch)
        _, cols, rows, cw, ch = best
        order = sorted(g["slots"], key=lambda s: (not targeted(s), not s["done"]))
        mine = [s for s in g["slots"] if targeted(s)]
        gd, gt, gn = sum(s["done"] for s in mine), len(mine), n - len(mine)
        gtip = f'{g["name"]}: {gd}/{gt}' + (f', and {gn} {newer_text}' if gn else "")
        parts.append(f'<g><title>{html.escape(gtip)}</title>')
        for i, s in enumerate(order):
            r, c = divmod(i, cols)
            state = ("done" if s["done"] else "missing") if targeted(s) else ("done, " if s["done"] else "") + newer_text
            fill = THEME["done"] if s["done"] else THEME["missing"] if targeted(s) else "url(#newer)"
            tip = f'{s["name"]}: {state} - {s["reason"]}'
            parts.append(f'<rect x="{fmt(gx + c * cw)}" y="{fmt(gy + r * ch)}" width="{fmt(cw)}" height="{fmt(ch)}" '
                         f'fill="{fill}" stroke="{THEME["panel"]}" stroke-width="0.75">'
                         f'<title>{html.escape(tip)}</title></rect>')
        parts.append("</g>")
        label = f'{g["name"]} {gd}/{gt}'
        size = 12
        fits = text_width(label, size) + 8 <= gw and gh >= 20
        if not fits:
            label, size = f'{g["name"]} {gd}/{gt}', 10
            fits = text_width(label, size) + 6 <= gw and gh >= 16
        if fits:
            parts.append(f'<text x="{fmt(gx + 4)}" y="{fmt(gy + size + 2)}" font-size="{size}" font-weight="600" '
                         f'fill="{THEME["text"]}" stroke="{THEME["halo"]}" stroke-width="3" stroke-linejoin="round" '
                         f'paint-order="stroke">{html.escape(label)}</text>')
        else:
            hidden.append(f'[{len(hidden) + 1}] {g["name"]} {gd}/{gt}')
            parts.append(f'<text x="{fmt(gx + 3)}" y="{fmt(gy + 12)}" font-size="11" font-weight="600" '
                         f'fill="{THEME["text"]}" stroke="{THEME["halo"]}" stroke-width="3" stroke-linejoin="round" '
                         f'paint-order="stroke">{len(hidden)}</text>')
    title = f'{metric["title"]}: {done} of {total} slots done ({pct(done, total)})'
    sub = metric["subtitle"]
    foot_y = head + map_h + 20
    keys = [("done", THEME["done"]), ("missing", THEME["missing"])] + ([(newer_text, "url(#newer)")] if newer else [])
    legend, lx = "", pad
    for text, fill in keys:
        legend += (f'<rect x="{fmt(lx)}" y="{foot_y - 10}" width="11" height="11" fill="{fill}"/>'
                   f'<text x="{fmt(lx + 16)}" y="{foot_y}" font-size="12" fill="{THEME["muted"]}">'
                   f'{html.escape(text)}</text>')
        lx += 16 + text_width(text, 12) + 18
    legend += (f'<text x="{fmt(lx + 6)}" y="{foot_y}" font-size="12" fill="{THEME["muted"]}">'
               f'one cell per slot, one rectangle per group, area = slot count</text>')
    defs = ""
    if newer:
        # Hatched: a slot of an interface version newer than the one the driver declares. Not in the count.
        defs = (f'<defs><pattern id="newer" width="5" height="5" patternUnits="userSpaceOnUse" '
                f'patternTransform="rotate(45)"><rect width="5" height="5" fill="{THEME["bg"]}"/>'
                f'<rect width="2" height="5" fill="{THEME["missing"]}"/></pattern></defs>\n')
    lines = []
    if hidden:
        lines.append("Small groups: " + ", ".join(hidden))
    height = foot_y + 10 + 18 * len(lines)
    extra = "".join(f'<text x="{pad}" y="{foot_y + 18 * (k + 1)}" font-size="12" fill="{THEME["muted"]}">'
                    f'{html.escape(t)}</text>' for k, t in enumerate(lines))
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
            f'viewBox="0 0 {width} {height}" role="img" aria-label="{html.escape(title)}" '
            f'font-family="{html.escape(FONT)}">\n'
            f'<title>{html.escape(title)}</title>\n' + defs +
            f'<rect x="0.5" y="0.5" width="{width - 1}" height="{height - 1}" rx="6" fill="{THEME["panel"]}" '
            f'stroke="{THEME["border"]}"/>\n'
            f'<text x="{pad}" y="22" font-size="16" font-weight="600" fill="{THEME["text"]}">{html.escape(title)}</text>\n'
            f'<text x="{pad}" y="39" font-size="12" fill="{THEME["muted"]}">{html.escape(sub)}</text>\n'
            + "\n".join(parts) + "\n" + legend + extra + "\n</svg>\n")


def badge_svg(label: str, value: float, text: str) -> str:
    color = ("#e05d44" if value < 25 else "#fe7d37" if value < 50 else "#dfb317" if value < 75
             else "#a4a61d" if value < 90 else "#4c1")
    lw = round(text_width(label, 11) * 1.08 + 12)
    vw = round(text_width(text, 11) * 1.08 + 12)
    w = lw + vw
    esc = html.escape
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="20" role="img" '
            f'aria-label="{esc(label)}: {esc(text)}">\n<title>{esc(label)}: {esc(text)}</title>\n'
            f'<linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/>'
            f'<stop offset="1" stop-opacity=".1"/></linearGradient>\n'
            f'<clipPath id="r"><rect width="{w}" height="20" rx="3" fill="#fff"/></clipPath>\n'
            f'<g clip-path="url(#r)"><rect width="{lw}" height="20" fill="#555"/>'
            f'<rect x="{lw}" width="{vw}" height="20" fill="{color}"/><rect width="{w}" height="20" fill="url(#s)"/></g>\n'
            f'<g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11">'
            f'<text x="{lw / 2:.1f}" y="15" fill="#010101" fill-opacity=".3">{esc(label)}</text>'
            f'<text x="{lw / 2:.1f}" y="14">{esc(label)}</text>'
            f'<text x="{lw + vw / 2:.1f}" y="15" fill="#010101" fill-opacity=".3">{esc(text)}</text>'
            f'<text x="{lw + vw / 2:.1f}" y="14">{esc(text)}</text></g>\n</svg>\n')


# ---- outputs ---------------------------------------------------------------------------------------------------------

def targeted(slot: dict) -> bool:
    """A slot of an interface version that the driver declares, or of an older one. Only these are counted."""
    return slot.get("targeted", True)


def counts(metric: dict, every: bool = False) -> tuple[int, int, int]:
    slots = [s for g in metric["groups"] for s in g["slots"] if every or targeted(s)]
    return (sum(s["done"] for s in slots), len(slots), sum(1 for s in slots if s["done"] and s.get("partial")))


def readme_block(kmd: dict, umd: dict) -> str:
    kd, kt, kp = counts(kmd)
    ud, ut, up = counts(umd)
    ad, at, _ = counts(kmd, every=True)
    newer = at - kt
    first = sorted({s["since"] for g in kmd["groups"] for s in g["slots"] if not targeted(s)},
                   key=lambda v: kmd["interface_versions"]["values"][v])
    label = kmd["declared_label"]
    fs = sum(1 for g in umd["groups"] for s in g["slots"] if s.get("function") == "FailSafe")
    tables = ", ".join(f'`{g["struct"]}`' for g in umd["groups"])
    return "\n".join([
        BEGIN,
        "",
        '<img src="docs/status/badge-kmd-ddi.svg" alt="kernel-mode DDI: ' + pct(kd, kt) + '"> '
        '<img src="docs/status/badge-d3d12-ddi.svg" alt="D3D12 DDI: ' + pct(ud, ut) + '">',
        "",
        '<img src="docs/status/kmd-ddi.svg" width="860" alt="Treemap of the kernel-mode DDI slots">',
        "",
        f"Kernel-mode DDI: the driver fills {kd} of {kt} slots with a function that does work ({pct(kd, kt)}). "
        f"The total is every function slot of `DRIVER_INITIALIZATION_DATA` in `{KMD_HEADER}` of "
        f"WDK {WDK_VERSION[:-2]}, up to the interface version that the driver declares in `WddmBuildTable` "
        f"(`{kmd['declared_version']}`, {label}). "
        f"The map also shows the {newer} slots of {version_label(first[0]) if first else 'later versions'} "
        f"and later as hatched cells. The driver does not target these versions yet. "
        f"For all {at} slots of all interface versions, the driver fills {ad} ({pct(ad, at)}). "
        "The header reserves the members of type `PVOID`, so they are not slots.",
        "",
        '<img src="docs/status/d3d12-ddi.svg" width="860" alt="Treemap of the D3D12 user-mode DDI slots">',
        "",
        f"D3D12 user-mode DDI: the driver fills {ud} of {ut} slots with a function that does work "
        f"({pct(ud, ut)}). The total is every function slot of the tables that the driver gives the runtime "
        f"at DDI build {umd['build']}: {tables}. "
        "The command-list count is for the graphics table. "
        f"The newer tables of `{UMD_HEADER}` are not in the total. "
        f"Of the missing slots, {fs} hold a fail-safe entry of engine-ddi.",
        "",
        "The two maps use one rule. A slot counts as done when its function can return success and does work. "
        "A function that only logs, counts, reports an error or writes zeros does no work. "
        "A function that returns `E_NOTIMPL`, `STATUS_NOT_SUPPORTED` or another failure constant on every path "
        "does no work. "
        f"A done slot can refuse some inputs: {kp} kernel-mode and {up} user-mode slots do this. "
        "The script `tools/docs/status_map.py` reads the source. It does not build or run the driver, so done "
        "means that the code exists, not that a test passed. "
        "The file `docs/status/status.json` gives each slot with its function, source line and reason.",
        "",
        END,
    ])


def build(kits: Path | None) -> dict[Path, str]:
    prior = json.loads(JSON_PATH.read_text(encoding="utf-8")) if JSON_PATH.exists() else None
    if kits is None and prior is None:
        raise SystemExit("status_map: no --kits and no committed status.json to take the WDK slot lists from")
    kmd = kmd_metric(kits, prior["metrics"][0] if prior else None)
    umd = umd_metric(kits, prior["metrics"][1] if prior else None)
    kmd["subtitle"] = (f"DRIVER_INITIALIZATION_DATA, WDK {WDK_VERSION[:-2]}, counted up to {kmd['declared_label']}. "
                       f"Done: WddmBuildTable sets the slot to a function that does work.")
    umd["subtitle"] = (f"Tables given to the D3D12 runtime at DDI build {umd['build']}. "
                       f"Done: the function of the slot does work. A fail-safe entry is not done.")
    out = {}
    doc = {"generator": "tools/docs/status_map.py", "rule": RULE, "neutral_calls": sorted(NEUTRAL),
           "failure_constants": sorted(REFUSAL), "metrics": []}
    for metric, label in ((kmd, "KMD DDI"), (umd, "D3D12 DDI")):
        d, t, p = counts(metric)
        metric["summary"] = {"done": d, "total": t, "partial": p, "percent": round(100.0 * d / t, 2)}
        ad, at, ap = counts(metric, every=True)
        if at != t:
            metric["summary"]["all_versions"] = {"done": ad, "total": at, "partial": ap,
                                                 "percent": round(100.0 * ad / at, 2)}
        doc["metrics"].append({k: v for k, v in metric.items() if k != "subtitle"})
        out[OUT_DIR / f'{metric["id"]}.svg'] = treemap_svg(metric)
        out[OUT_DIR / f'badge-{metric["id"]}.svg'] = badge_svg(label, 100.0 * d / t, pct(d, t))
    out[JSON_PATH] = json.dumps(doc, indent=1, sort_keys=False) + "\n"
    text = README.read_text(encoding="utf-8")
    block = readme_block(kmd, umd)
    if BEGIN in text and END in text:
        a, b = text.index(BEGIN), text.index(END) + len(END)
        text = text[:a] + block + text[b:]
    else:
        raise SystemExit(f"status_map: README.md has no '{BEGIN}' marker")
    out[README] = text
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--kits", type=Path, default=os.environ.get("BC250_KITS") or None,
                    help="directory that holds the WDK NuGet packages (else BC250_KITS, else status.json)")
    ap.add_argument("--check", action="store_true", help="exit 1 if a committed output differs from a fresh run")
    args = ap.parse_args(argv)
    kits = Path(args.kits) if args.kits else None
    if kits is None:
        print("status_map: no --kits; the WDK slot lists come from the committed status.json", file=sys.stderr)
    out = build(kits)
    if args.check:
        stale = [p for p, t in out.items()
                 if not p.exists() or p.read_text(encoding="utf-8").replace("\r\n", "\n") != t]
        for p in stale:
            print(f"status_map: stale {p.relative_to(REPO).as_posix()}", file=sys.stderr)
        if stale:
            print("status_map: run python tools/docs/status_map.py --kits <WDK dir> and commit the result",
                  file=sys.stderr)
            return 1
        print(f"status_map: {len(out)} outputs match")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for p, t in out.items():
        with open(p, "w", encoding="utf-8", newline="\n") as f:
            f.write(t)
    for m in json.loads(out[JSON_PATH])["metrics"]:
        s = m["summary"]
        print(f'{m["id"]}: {s["done"]}/{s["total"]} = {s["percent"]}% (partial {s["partial"]})')
    return 0


if __name__ == "__main__":
    sys.exit(main())
