// SPDX-License-Identifier: MIT
// Generated by format-list.py from D3D11_3_Formats_FL11_1.xls; do not edit.
// PROVENANCE: github.com/microsoft/DirectX-Specs d3d/archive/images/d3d11/D3D11_3_Formats_FL11_1.xls (CC-BY-4.0).
#pragma once

namespace engine_ddi {

struct FormatListEntry { DXGI_FORMAT format; UINT allowed; UINT required; };

// The D3D12DDI_FORMAT_SUPPORT bits a format may and must carry at feature level 11_1.
inline constexpr FormatListEntry kFormatList[] = {
    // UNKNOWN may: buffer tiled
    //        must: buffer
    {DXGI_FORMAT_UNKNOWN, 0x00010400u, 0x00000400u},
    // R32G32B32A32_TYPELESS may: tiled
    //                      must: -
    {DXGI_FORMAT_R32G32B32A32_TYPELESS, 0x00010000u, 0x00000000u},
    // R32G32B32A32_FLOAT may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //                   must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R32G32B32A32_FLOAT, 0x0003471Fu, 0x0000471Fu},
    // R32G32B32A32_UINT may: rt msaa_rt msaa_load vb uav_w buffer logic_op tiled uav_r
    //                  must: rt msaa_rt msaa_load vb uav_w buffer logic_op
    {DXGI_FORMAT_R32G32B32A32_UINT, 0x0003271Au, 0x0000271Au},
    // R32G32B32A32_SINT may: rt msaa_rt msaa_load vb uav_w buffer tiled uav_r
    //                  must: rt msaa_rt msaa_load vb uav_w buffer
    {DXGI_FORMAT_R32G32B32A32_SINT, 0x0003071Au, 0x0000071Au},
    // R32G32B32_TYPELESS may: -
    //                   must: -
    {DXGI_FORMAT_R32G32B32_TYPELESS, 0x00000000u, 0x00000000u},
    // R32G32B32_FLOAT may: sample rt blend msaa_rt msaa_load vb buffer gather
    //                must: msaa_load vb buffer
    {DXGI_FORMAT_R32G32B32_FLOAT, 0x0000451Fu, 0x00000510u},
    // R32G32B32_UINT may: rt msaa_rt msaa_load vb buffer logic_op
    //               must: msaa_load vb buffer logic_op
    {DXGI_FORMAT_R32G32B32_UINT, 0x0000251Au, 0x00002510u},
    // R32G32B32_SINT may: rt msaa_rt msaa_load vb buffer
    //               must: msaa_load vb buffer
    {DXGI_FORMAT_R32G32B32_SINT, 0x0000051Au, 0x00000510u},
    // R16G16B16A16_TYPELESS may: tiled
    //                      must: -
    {DXGI_FORMAT_R16G16B16A16_TYPELESS, 0x00010000u, 0x00000000u},
    // R16G16B16A16_FLOAT may: sample rt blend msaa_rt msaa_load vp_out vp_in vb uav_w buffer gather tiled uav_r
    //                   must: sample rt blend msaa_rt msaa_load vp_out vb uav_w buffer gather
    {DXGI_FORMAT_R16G16B16A16_FLOAT, 0x000347DFu, 0x0000475Fu},
    // R16G16B16A16_UNORM may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //                   must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R16G16B16A16_UNORM, 0x0003471Fu, 0x0000471Fu},
    // R16G16B16A16_UINT may: rt msaa_rt msaa_load vb uav_w buffer logic_op tiled uav_r
    //                  must: rt msaa_rt msaa_load vb uav_w buffer logic_op
    {DXGI_FORMAT_R16G16B16A16_UINT, 0x0003271Au, 0x0000271Au},
    // R16G16B16A16_SNORM may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //                   must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R16G16B16A16_SNORM, 0x0003471Fu, 0x0000471Fu},
    // R16G16B16A16_SINT may: rt msaa_rt msaa_load vb uav_w buffer tiled uav_r
    //                  must: rt msaa_rt msaa_load vb uav_w buffer
    {DXGI_FORMAT_R16G16B16A16_SINT, 0x0003071Au, 0x0000071Au},
    // R32G32_TYPELESS may: tiled
    //                must: -
    {DXGI_FORMAT_R32G32_TYPELESS, 0x00010000u, 0x00000000u},
    // R32G32_FLOAT may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //             must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R32G32_FLOAT, 0x0003471Fu, 0x0000471Fu},
    // R32G32_UINT may: rt msaa_rt msaa_load vb uav_w buffer logic_op tiled uav_r
    //            must: rt msaa_rt msaa_load vb uav_w buffer logic_op
    {DXGI_FORMAT_R32G32_UINT, 0x0003271Au, 0x0000271Au},
    // R32G32_SINT may: rt msaa_rt msaa_load vb uav_w buffer tiled uav_r
    //            must: rt msaa_rt msaa_load vb uav_w buffer
    {DXGI_FORMAT_R32G32_SINT, 0x0003071Au, 0x0000071Au},
    // R32G8X24_TYPELESS may: -
    //                  must: -
    {DXGI_FORMAT_R32G8X24_TYPELESS, 0x00000000u, 0x00000000u},
    // D32_FLOAT_S8X24_UINT may: msaa_rt
    //                     must: msaa_rt
    {DXGI_FORMAT_D32_FLOAT_S8X24_UINT, 0x00000008u, 0x00000008u},
    // R32_FLOAT_X8X24_TYPELESS may: sample msaa_load gather
    //                         must: sample msaa_load gather
    {DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS, 0x00004011u, 0x00004011u},
    // X32_TYPELESS_G8X24_UINT may: msaa_load
    //                        must: msaa_load
    {DXGI_FORMAT_X32_TYPELESS_G8X24_UINT, 0x00000010u, 0x00000010u},
    // R10G10B10A2_TYPELESS may: tiled
    //                     must: -
    {DXGI_FORMAT_R10G10B10A2_TYPELESS, 0x00010000u, 0x00000000u},
    // R10G10B10A2_UNORM may: sample rt blend msaa_rt msaa_load vp_out vp_in vb uav_w buffer gather tiled uav_r
    //                  must: sample rt blend msaa_rt msaa_load vp_out vb uav_w buffer gather
    {DXGI_FORMAT_R10G10B10A2_UNORM, 0x000347DFu, 0x0000475Fu},
    // R10G10B10A2_UINT may: rt msaa_rt msaa_load vb uav_w buffer logic_op tiled uav_r
    //                 must: rt msaa_rt msaa_load vb uav_w buffer logic_op
    {DXGI_FORMAT_R10G10B10A2_UINT, 0x0003271Au, 0x0000271Au},
    // R11G11B10_FLOAT may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //                must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R11G11B10_FLOAT, 0x0003471Fu, 0x0000471Fu},
    // R8G8B8A8_TYPELESS may: tiled
    //                  must: -
    {DXGI_FORMAT_R8G8B8A8_TYPELESS, 0x00010000u, 0x00000000u},
    // R8G8B8A8_UNORM may: sample rt blend msaa_rt msaa_load vp_out vp_in vb uav_w buffer gather tiled uav_r
    //               must: sample rt blend msaa_rt msaa_load vp_out vb uav_w buffer gather
    {DXGI_FORMAT_R8G8B8A8_UNORM, 0x000347DFu, 0x0000475Fu},
    // R8G8B8A8_UNORM_SRGB may: sample rt blend msaa_rt msaa_load vp_out vp_in gather tiled
    //                    must: sample rt blend msaa_rt msaa_load vp_out gather
    {DXGI_FORMAT_R8G8B8A8_UNORM_SRGB, 0x000140DFu, 0x0000405Fu},
    // R8G8B8A8_UINT may: rt msaa_rt msaa_load vb uav_w buffer logic_op tiled uav_r
    //              must: rt msaa_rt msaa_load vb uav_w buffer logic_op
    {DXGI_FORMAT_R8G8B8A8_UINT, 0x0003271Au, 0x0000271Au},
    // R8G8B8A8_SNORM may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //               must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R8G8B8A8_SNORM, 0x0003471Fu, 0x0000471Fu},
    // R8G8B8A8_SINT may: rt msaa_rt msaa_load vb uav_w buffer tiled uav_r
    //              must: rt msaa_rt msaa_load vb uav_w buffer
    {DXGI_FORMAT_R8G8B8A8_SINT, 0x0003071Au, 0x0000071Au},
    // R16G16_TYPELESS may: tiled
    //                must: -
    {DXGI_FORMAT_R16G16_TYPELESS, 0x00010000u, 0x00000000u},
    // R16G16_FLOAT may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //             must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R16G16_FLOAT, 0x0003471Fu, 0x0000471Fu},
    // R16G16_UNORM may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //             must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R16G16_UNORM, 0x0003471Fu, 0x0000471Fu},
    // R16G16_UINT may: rt msaa_rt msaa_load vb uav_w buffer logic_op tiled uav_r
    //            must: rt msaa_rt msaa_load vb uav_w buffer logic_op
    {DXGI_FORMAT_R16G16_UINT, 0x0003271Au, 0x0000271Au},
    // R16G16_SNORM may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //             must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R16G16_SNORM, 0x0003471Fu, 0x0000471Fu},
    // R16G16_SINT may: rt msaa_rt msaa_load vb uav_w buffer tiled uav_r
    //            must: rt msaa_rt msaa_load vb uav_w buffer
    {DXGI_FORMAT_R16G16_SINT, 0x0003071Au, 0x0000071Au},
    // R32_TYPELESS may: tiled
    //             must: -
    {DXGI_FORMAT_R32_TYPELESS, 0x00010000u, 0x00000000u},
    // D32_FLOAT may: msaa_rt tiled
    //          must: msaa_rt
    {DXGI_FORMAT_D32_FLOAT, 0x00010008u, 0x00000008u},
    // R32_FLOAT may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //          must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather uav_r
    {DXGI_FORMAT_R32_FLOAT, 0x0003471Fu, 0x0002471Fu},
    // R32_UINT may: rt msaa_rt msaa_load vb uav_w buffer logic_op tiled uav_r
    //         must: rt msaa_rt msaa_load vb uav_w buffer logic_op uav_r
    {DXGI_FORMAT_R32_UINT, 0x0003271Au, 0x0002271Au},
    // R32_SINT may: rt msaa_rt msaa_load vb uav_w buffer tiled uav_r
    //         must: rt msaa_rt msaa_load vb uav_w buffer uav_r
    {DXGI_FORMAT_R32_SINT, 0x0003071Au, 0x0002071Au},
    // R24G8_TYPELESS may: -
    //               must: -
    {DXGI_FORMAT_R24G8_TYPELESS, 0x00000000u, 0x00000000u},
    // D24_UNORM_S8_UINT may: msaa_rt
    //                  must: msaa_rt
    {DXGI_FORMAT_D24_UNORM_S8_UINT, 0x00000008u, 0x00000008u},
    // R24_UNORM_X8_TYPELESS may: sample msaa_load gather
    //                      must: sample msaa_load gather
    {DXGI_FORMAT_R24_UNORM_X8_TYPELESS, 0x00004011u, 0x00004011u},
    // X24_TYPELESS_G8_UINT may: msaa_load
    //                     must: msaa_load
    {DXGI_FORMAT_X24_TYPELESS_G8_UINT, 0x00000010u, 0x00000010u},
    // R8G8_TYPELESS may: tiled
    //              must: -
    {DXGI_FORMAT_R8G8_TYPELESS, 0x00010000u, 0x00000000u},
    // R8G8_UNORM may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //           must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R8G8_UNORM, 0x0003471Fu, 0x0000471Fu},
    // R8G8_UINT may: rt msaa_rt msaa_load vb uav_w buffer logic_op tiled uav_r
    //          must: rt msaa_rt msaa_load vb uav_w buffer logic_op
    {DXGI_FORMAT_R8G8_UINT, 0x0003271Au, 0x0000271Au},
    // R8G8_SNORM may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //           must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R8G8_SNORM, 0x0003471Fu, 0x0000471Fu},
    // R8G8_SINT may: rt msaa_rt msaa_load vb uav_w buffer tiled uav_r
    //          must: rt msaa_rt msaa_load vb uav_w buffer
    {DXGI_FORMAT_R8G8_SINT, 0x0003071Au, 0x0000071Au},
    // R16_TYPELESS may: tiled
    //             must: -
    {DXGI_FORMAT_R16_TYPELESS, 0x00010000u, 0x00000000u},
    // R16_FLOAT may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //          must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R16_FLOAT, 0x0003471Fu, 0x0000471Fu},
    // D16_UNORM may: msaa_rt tiled
    //          must: msaa_rt
    {DXGI_FORMAT_D16_UNORM, 0x00010008u, 0x00000008u},
    // R16_UNORM may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //          must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R16_UNORM, 0x0003471Fu, 0x0000471Fu},
    // R16_UINT may: rt msaa_rt msaa_load vb uav_w buffer logic_op tiled uav_r
    //         must: rt msaa_rt msaa_load vb uav_w buffer logic_op
    {DXGI_FORMAT_R16_UINT, 0x0003271Au, 0x0000271Au},
    // R16_SNORM may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //          must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R16_SNORM, 0x0003471Fu, 0x0000471Fu},
    // R16_SINT may: rt msaa_rt msaa_load vb uav_w buffer tiled uav_r
    //         must: rt msaa_rt msaa_load vb uav_w buffer
    {DXGI_FORMAT_R16_SINT, 0x0003071Au, 0x0000071Au},
    // R8_TYPELESS may: tiled
    //            must: -
    {DXGI_FORMAT_R8_TYPELESS, 0x00010000u, 0x00000000u},
    // R8_UNORM may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //         must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R8_UNORM, 0x0003471Fu, 0x0000471Fu},
    // R8_UINT may: rt msaa_rt msaa_load vb uav_w buffer logic_op tiled uav_r
    //        must: rt msaa_rt msaa_load vb uav_w buffer logic_op
    {DXGI_FORMAT_R8_UINT, 0x0003271Au, 0x0000271Au},
    // R8_SNORM may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //         must: sample rt blend msaa_rt msaa_load vb uav_w buffer gather
    {DXGI_FORMAT_R8_SNORM, 0x0003471Fu, 0x0000471Fu},
    // R8_SINT may: rt msaa_rt msaa_load vb uav_w buffer tiled uav_r
    //        must: rt msaa_rt msaa_load vb uav_w buffer
    {DXGI_FORMAT_R8_SINT, 0x0003071Au, 0x0000071Au},
    // A8_UNORM may: sample rt blend msaa_rt msaa_load uav_w gather tiled uav_r
    //         must: sample rt blend msaa_rt msaa_load uav_w gather
    {DXGI_FORMAT_A8_UNORM, 0x0003421Fu, 0x0000421Fu},
    // R9G9B9E5_SHAREDEXP may: sample gather tiled
    //                   must: sample gather
    {DXGI_FORMAT_R9G9B9E5_SHAREDEXP, 0x00014001u, 0x00004001u},
    // R8G8_B8G8_UNORM may: sample gather
    //                must: sample gather
    {DXGI_FORMAT_R8G8_B8G8_UNORM, 0x00004001u, 0x00004001u},
    // G8R8_G8B8_UNORM may: sample gather
    //                must: sample gather
    {DXGI_FORMAT_G8R8_G8B8_UNORM, 0x00004001u, 0x00004001u},
    // BC1_TYPELESS may: tiled
    //             must: -
    {DXGI_FORMAT_BC1_TYPELESS, 0x00010000u, 0x00000000u},
    // BC1_UNORM may: sample gather tiled
    //          must: sample gather
    {DXGI_FORMAT_BC1_UNORM, 0x00014001u, 0x00004001u},
    // BC1_UNORM_SRGB may: sample gather tiled
    //               must: sample gather
    {DXGI_FORMAT_BC1_UNORM_SRGB, 0x00014001u, 0x00004001u},
    // BC2_TYPELESS may: tiled
    //             must: -
    {DXGI_FORMAT_BC2_TYPELESS, 0x00010000u, 0x00000000u},
    // BC2_UNORM may: sample gather tiled
    //          must: sample gather
    {DXGI_FORMAT_BC2_UNORM, 0x00014001u, 0x00004001u},
    // BC2_UNORM_SRGB may: sample gather tiled
    //               must: sample gather
    {DXGI_FORMAT_BC2_UNORM_SRGB, 0x00014001u, 0x00004001u},
    // BC3_TYPELESS may: tiled
    //             must: -
    {DXGI_FORMAT_BC3_TYPELESS, 0x00010000u, 0x00000000u},
    // BC3_UNORM may: sample gather tiled
    //          must: sample gather
    {DXGI_FORMAT_BC3_UNORM, 0x00014001u, 0x00004001u},
    // BC3_UNORM_SRGB may: sample gather tiled
    //               must: sample gather
    {DXGI_FORMAT_BC3_UNORM_SRGB, 0x00014001u, 0x00004001u},
    // BC4_TYPELESS may: tiled
    //             must: -
    {DXGI_FORMAT_BC4_TYPELESS, 0x00010000u, 0x00000000u},
    // BC4_UNORM may: sample gather tiled
    //          must: sample gather
    {DXGI_FORMAT_BC4_UNORM, 0x00014001u, 0x00004001u},
    // BC4_SNORM may: sample gather tiled
    //          must: sample gather
    {DXGI_FORMAT_BC4_SNORM, 0x00014001u, 0x00004001u},
    // BC5_TYPELESS may: tiled
    //             must: -
    {DXGI_FORMAT_BC5_TYPELESS, 0x00010000u, 0x00000000u},
    // BC5_UNORM may: sample gather tiled
    //          must: sample gather
    {DXGI_FORMAT_BC5_UNORM, 0x00014001u, 0x00004001u},
    // BC5_SNORM may: sample gather tiled
    //          must: sample gather
    {DXGI_FORMAT_BC5_SNORM, 0x00014001u, 0x00004001u},
    // B5G6R5_UNORM may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //             must: sample rt blend msaa_rt msaa_load gather
    {DXGI_FORMAT_B5G6R5_UNORM, 0x0003471Fu, 0x0000401Fu},
    // B5G5R5A1_UNORM may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //               must: sample gather
    {DXGI_FORMAT_B5G5R5A1_UNORM, 0x0003471Fu, 0x00004001u},
    // B8G8R8A8_UNORM may: sample rt blend msaa_rt msaa_load vp_out vp_in vb buffer gather tiled
    //               must: sample rt blend msaa_rt msaa_load vp_out vb buffer gather
    {DXGI_FORMAT_B8G8R8A8_UNORM, 0x000145DFu, 0x0000455Fu},
    // B8G8R8X8_UNORM may: sample rt blend msaa_rt msaa_load vp_out vp_in vb buffer gather tiled
    //               must: sample rt blend msaa_rt msaa_load vb buffer gather
    {DXGI_FORMAT_B8G8R8X8_UNORM, 0x000145DFu, 0x0000451Fu},
    // R10G10B10_XR_BIAS_A2_UNORM may: vp_out vp_in tiled
    //                           must: vp_out
    {DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM, 0x000100C0u, 0x00000040u},
    // B8G8R8A8_TYPELESS may: tiled
    //                  must: -
    {DXGI_FORMAT_B8G8R8A8_TYPELESS, 0x00010000u, 0x00000000u},
    // B8G8R8A8_UNORM_SRGB may: sample rt blend msaa_rt msaa_load vp_out vp_in gather tiled
    //                    must: sample rt blend msaa_rt msaa_load vp_out gather
    {DXGI_FORMAT_B8G8R8A8_UNORM_SRGB, 0x000140DFu, 0x0000405Fu},
    // B8G8R8X8_TYPELESS may: tiled
    //                  must: -
    {DXGI_FORMAT_B8G8R8X8_TYPELESS, 0x00010000u, 0x00000000u},
    // B8G8R8X8_UNORM_SRGB may: sample rt blend msaa_rt msaa_load gather tiled
    //                    must: sample rt blend msaa_rt msaa_load gather
    {DXGI_FORMAT_B8G8R8X8_UNORM_SRGB, 0x0001401Fu, 0x0000401Fu},
    // BC6H_TYPELESS may: tiled
    //              must: -
    {DXGI_FORMAT_BC6H_TYPELESS, 0x00010000u, 0x00000000u},
    // BC6H_UF16 may: sample gather tiled
    //          must: sample gather
    {DXGI_FORMAT_BC6H_UF16, 0x00014001u, 0x00004001u},
    // BC6H_SF16 may: sample gather tiled
    //          must: sample gather
    {DXGI_FORMAT_BC6H_SF16, 0x00014001u, 0x00004001u},
    // BC7_TYPELESS may: tiled
    //             must: -
    {DXGI_FORMAT_BC7_TYPELESS, 0x00010000u, 0x00000000u},
    // BC7_UNORM may: sample gather tiled
    //          must: sample gather
    {DXGI_FORMAT_BC7_UNORM, 0x00014001u, 0x00004001u},
    // BC7_UNORM_SRGB may: sample gather tiled
    //               must: sample gather
    {DXGI_FORMAT_BC7_UNORM_SRGB, 0x00014001u, 0x00004001u},
    // AYUV may: sample rt blend dec_out vp_out vp_in uav_w gather uav_r
    //     must: sample rt blend vp_in uav_w gather
    {DXGI_FORMAT_AYUV, 0x000242E7u, 0x00004287u},
    // Y410 may: sample dec_out vp_out vp_in uav_w gather uav_r
    //     must: sample uav_w gather
    {DXGI_FORMAT_Y410, 0x000242E1u, 0x00004201u},
    // Y416 may: sample dec_out vp_out vp_in uav_w gather uav_r
    //     must: sample uav_w gather
    {DXGI_FORMAT_Y416, 0x000242E1u, 0x00004201u},
    // NV12 may: sample rt blend dec_out vp_out vp_in uav_w gather uav_r
    //     must: sample rt blend dec_out vp_out vp_in uav_w gather
    {DXGI_FORMAT_NV12, 0x000242E7u, 0x000042E7u},
    // P010 may: sample rt blend dec_out vp_out vp_in uav_w gather uav_r
    //     must: sample rt blend uav_w gather
    {DXGI_FORMAT_P010, 0x000242E7u, 0x00004207u},
    // P016 may: sample rt blend dec_out vp_out vp_in uav_w gather uav_r
    //     must: sample rt blend uav_w gather
    {DXGI_FORMAT_P016, 0x000242E7u, 0x00004207u},
    // 420_OPAQUE may: dec_out vp_out vp_in
    //           must: dec_out vp_out vp_in
    {DXGI_FORMAT_420_OPAQUE, 0x000000E0u, 0x000000E0u},
    // YUY2 may: sample dec_out vp_out vp_in uav_w gather uav_r
    //     must: sample vp_in uav_w gather
    {DXGI_FORMAT_YUY2, 0x000242E1u, 0x00004281u},
    // Y210 may: sample dec_out vp_out vp_in uav_w gather uav_r
    //     must: sample uav_w gather
    {DXGI_FORMAT_Y210, 0x000242E1u, 0x00004201u},
    // Y216 may: sample dec_out vp_out vp_in uav_w gather uav_r
    //     must: sample uav_w gather
    {DXGI_FORMAT_Y216, 0x000242E1u, 0x00004201u},
    // NV11 may: sample rt blend dec_out vp_out vp_in uav_w gather uav_r
    //     must: sample rt blend uav_w gather
    {DXGI_FORMAT_NV11, 0x000242E7u, 0x00004207u},
    // AI44 may: vp_in
    //     must: vp_in
    {DXGI_FORMAT_AI44, 0x00000080u, 0x00000080u},
    // IA44 may: vp_in
    //     must: vp_in
    {DXGI_FORMAT_IA44, 0x00000080u, 0x00000080u},
    // P8 may: vp_in
    //   must: vp_in
    {DXGI_FORMAT_P8, 0x00000080u, 0x00000080u},
    // A8P8 may: vp_in
    //     must: vp_in
    {DXGI_FORMAT_A8P8, 0x00000080u, 0x00000080u},
    // B4G4R4A4_UNORM may: sample rt blend msaa_rt msaa_load vb uav_w buffer gather tiled uav_r
    //               must: sample gather
    {DXGI_FORMAT_B4G4R4A4_UNORM, 0x0003471Fu, 0x00004001u},
};

} // namespace engine_ddi
