# SPDX-License-Identifier: MIT
# Generates format-list.h from the D3D11.3 functional spec's FL11_1 format list (an Excel 2003 XML workbook):
#   python format-list.py <DirectX-Specs>/d3d/archive/images/d3d11/D3D11_3_Formats_FL11_1.xls \
#       <WDK>/Include/10.0.26100.0/um/d3d12umddi.h > format-list.h
# For every listed DXGI_FORMAT it writes the D3D12DDI_FORMAT_SUPPORT bits the list allows ('R', 'o' or 'd' in the
# capability's column) and requires ('R'). DISPLAY is never allowed: the DDI defines it from version 107 on
# (DirectX-Specs d3d/D3D12R9G9B9E5Format.md), and engine-ddi speaks 0092. Nor are CAPTURE and VIDEO_ENCODER, which
# the list has no column for, or MULTIPLANE_OVERLAY, which that document groups with DISPLAY (all or nothing).
# UAV_READS is allowed only on the formats DirectX-Specs d3d/UAVTypedLoad.md names (UAV_READS_FORMATS).
import sys
import xml.etree.ElementTree as ET

SS = '{urn:schemas-microsoft-com:office:spreadsheet}'


def rows(path):
    ws = ET.parse(path).getroot().find(SS + 'Worksheet')
    for r in ws.iter(SS + 'Row'):
        cells = []
        for c in r.findall(SS + 'Cell'):
            idx = c.get(SS + 'Index')
            if idx:
                cells += [''] * (int(idx) - 1 - len(cells))
            d = c.find(SS + 'Data')
            cells.append(''.join(d.itertext()) if d is not None else '')
        yield cells


# Column index in the list (after '#', name and bits per element) -> DDI bit.
DDI = {
    'SHADER_SAMPLE': [10], 'RENDERTARGET': [17], 'BLENDABLE': [18], 'MULTISAMPLE_RENDERTARGET': [33, 34, 35],
    'MULTISAMPLE_LOAD': [37], 'DECODER_OUTPUT': [40], 'VIDEO_PROCESSOR_OUTPUT': [42],
    'VIDEO_PROCESSOR_INPUT': [41], 'VERTEX_BUFFER': [2], 'UAV_WRITES': [23], 'BUFFER': [1],
    'OUTPUT_MERGER_LOGIC_OP': [19], 'SHADER_GATHER': [13], 'TILED': [44],
    # Typed UAV loads: allowed where typed UAVs are and the format is one of UAV_READS_FORMATS, required where the
    # list requires them (R32_FLOAT, R32_UINT, R32_SINT).
    'UAV_READS': [23],
}
REQUIRED = {'MULTISAMPLE_RENDERTARGET': [33], 'UAV_READS': [25]}

# The formats that may report UAV_READS, "all others should never set the _UAV_READS bit" (d3d/UAVTypedLoad.md,
# CheckFormatSupport). The video formats the list allows typed UAVs on (AYUV, Y410, Y416, NV12, P010, P016, YUY2,
# Y210, Y216, NV11) are not among them.
UAV_READS_FORMATS = {
    'R32G32B32A32_FLOAT', 'R32G32B32A32_UINT', 'R32G32B32A32_SINT', 'R16G16B16A16_FLOAT', 'R16G16B16A16_UNORM',
    'R16G16B16A16_UINT', 'R16G16B16A16_SNORM', 'R16G16B16A16_SINT', 'R32G32_FLOAT', 'R32G32_UINT', 'R32G32_SINT',
    'R10G10B10A2_UNORM', 'R10G10B10A2_UINT', 'R11G11B10_FLOAT', 'R8G8B8A8_UNORM', 'R8G8B8A8_UINT', 'R8G8B8A8_SNORM',
    'R8G8B8A8_SINT', 'R16G16_FLOAT', 'R16G16_UNORM', 'R16G16_UINT', 'R16G16_SNORM', 'R16G16_SINT', 'R32_FLOAT',
    'R32_UINT', 'R32_SINT', 'R8G8_UNORM', 'R8G8_UINT', 'R8G8_SNORM', 'R8G8_SINT', 'R16_FLOAT', 'R16_UNORM', 'R16_UINT',
    'R16_SNORM', 'R16_SINT', 'R8_UNORM', 'R8_UINT', 'R8_SNORM', 'R8_SINT', 'A8_UNORM', 'B5G6R5_UNORM',
    'B5G5R5A1_UNORM', 'B4G4R4A4_UNORM',
}


def main(path):
    table = []
    for r in rows(path):
        if len(r) > 2 and r[1].strip().isdigit() and r[2].strip():
            caps = (r[4:49] + [''] * 45)[:45]
            table.append((int(r[1]), r[2].strip(), caps))
    table.sort()
    bit_value = {}
    for line in open(header_path()):
        parts = line.split()
        if len(parts) >= 3 and parts[0] == '#define' and parts[1].startswith('D3D12DDI_FORMAT_SUPPORT_'):
            bit_value[parts[1][len('D3D12DDI_FORMAT_SUPPORT_'):]] = int(parts[2], 16)
    out = sys.stdout
    out.write('// SPDX-License-Identifier: MIT\n')
    out.write('// Generated by format-list.py from D3D11_3_Formats_FL11_1.xls; do not edit.\n')
    out.write('// PROVENANCE: github.com/microsoft/DirectX-Specs d3d/archive/images/d3d11/D3D11_3_Formats_FL11_1.xls '
              '(CC-BY-4.0).\n')
    out.write('#pragma once\n\nnamespace engine_ddi {\n\n')
    out.write('struct FormatListEntry { DXGI_FORMAT format; UINT allowed; UINT required; };\n\n')
    out.write('// The D3D12DDI_FORMAT_SUPPORT bits a format may and must carry at feature level 11_1, UAV_READS\n'
              '// only on the formats d3d/UAVTypedLoad.md of the same repository names.\n')
    out.write('inline constexpr FormatListEntry kFormatList[] = {\n')
    for n, name, caps in table:
        allowed, required = [], []
        for bit, cols in DDI.items():
            if bit == 'UAV_READS' and name not in UAV_READS_FORMATS:
                continue
            if any(caps[c] in ('R', 'o', 'd') for c in cols):
                allowed.append(bit)
            if any(caps[c] == 'R' for c in REQUIRED.get(bit, cols)):
                required.append(bit)
        mask = lambda bits: sum(bit_value[b] for b in bits)
        short = lambda bits: ' '.join(SHORT[b] for b in bits) or '-'
        out.write('    // %s may: %s\n' % (name, short(allowed)))
        out.write('    //%s must: %s\n' % (' ' * len(name), short(required)))
        out.write('    {DXGI_FORMAT_%s, 0x%08Xu, 0x%08Xu},\n' % (name, mask(allowed), mask(required)))
    out.write('};\n\n} // namespace engine_ddi\n')


SHORT = {
    'SHADER_SAMPLE': 'sample', 'RENDERTARGET': 'rt', 'BLENDABLE': 'blend', 'MULTISAMPLE_RENDERTARGET': 'msaa_rt',
    'MULTISAMPLE_LOAD': 'msaa_load', 'DECODER_OUTPUT': 'dec_out', 'VIDEO_PROCESSOR_OUTPUT': 'vp_out',
    'VIDEO_PROCESSOR_INPUT': 'vp_in', 'VERTEX_BUFFER': 'vb', 'UAV_WRITES': 'uav_w', 'BUFFER': 'buffer',
    'OUTPUT_MERGER_LOGIC_OP': 'logic_op', 'SHADER_GATHER': 'gather', 'TILED': 'tiled', 'UAV_READS': 'uav_r',
}


# d3d12umddi.h of the WDK the build uses: the flag values come from the header, not from this script.
def header_path():
    return sys.argv[2]


if __name__ == '__main__':
    main(sys.argv[1])
