#!/usr/bin/env python3
"""Generate regs.generated.h for bc250kmd: every BAR5 offset the miniport may touch, by name, from regcalc.

Nobody types an offset (docs/02-register-addressing.md). Two tables come out of this script:

  g_MmioReadAllow   the offsets the escape READ_REG may read: exactly the list tools/win/bc250rd reads, i.e.
                    registers that were read on unit A without harm and without side effects (facts M16, M25)
  g_MmioWriteAllow  the offsets the escape WRITE_REG may write. A register gets onto WRITABLE below by an
                    experiment that says why, never by convenience.
  g_MmioGartAllow   the offsets the kernel's GART command (gart.c) may touch, and nobody else: exactly the
                    registers amdgpu itself wrote on unit A during that step of its init, taken from the
                    recorded trace (E03), plus the two acknowledge registers it polled. Not chosen by us.

Run:  python driver/kmd/gen_regs.py
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(ROOT / "tools" / "regcalc"))
sys.path.insert(0, str(ROOT / "tools" / "diagusb"))
sys.path.insert(0, str(ROOT / "tools" / "trace"))
from regcalc import HDR_DIR, RegMap  # noqa: E402
from gen_probes import SPEC  # noqa: E402  (ip -> header)
from extract_phase import accesses  # noqa: E402

TRACE = ROOT / "evidence/linux/2026-09-21-E03-init-trace/amdgpu-events.txt"
# (table, experiment, regex on traced register names, end of the step in seconds since the first access,
#  registers the step only reads). gmc_v10_0_gart_enable() is over at 0.26 s (docs/init-sequence.md).
SEQUENCES = [
    ("Gart", "E09", r"^(GC\.(GCVM|GCMC)|MMHUB\.(MMVM|MMMC))", 0.26,
     [("GC", "mmGCVM_INVALIDATE_ENG17_ACK"), ("MMHUB", "mmMMVM_INVALIDATE_ENG17_ACK")]),
]

# (ip, register, experiment that put it here, why it is safe)
WRITABLE = [
    ("GC", "mmSCRATCH_REG0", "E07", "scratch, no function; amdgpu's own ring-test target, written 11 times during init (facts M24)"),
    ("GC", "mmSCRATCH_REG1", "E07", "scratch, no function; second control so that one lucky address cannot pass the test"),
]

# Named offsets the driver's own code uses (beyond the tables).
NAMED = [("GC", "mmSCRATCH_REG0"), ("GC", "mmSCRATCH_REG1"), ("GC", "mmGRBM_STATUS"),
         ("GC", "mmGCMC_VM_FB_OFFSET"), ("GC", "mmGCMC_VM_FB_LOCATION_BASE"), ("GC", "mmGCMC_VM_FB_LOCATION_TOP")]

BAR5_LENGTH = 0x80000     # BC250_BAR5_LENGTH in mmio.c

LINE = re.compile(r"^([A-Z0-9]+)\.(\S+) (0x[0-9a-f]+)$")


def offset(maps, ip, name):
    if ip not in maps:
        header = next(h for i, h, _ in SPEC if i == ip)
        maps[ip] = RegMap(ip=ip, reg_header=HDR_DIR / header)
    return maps[ip].byte_offset(name)


def main():
    maps = {}
    reads = sorted({int(m.group(3), 16) for m in map(LINE.match, (ROOT / "tools/win/bc250rd/reglist.txt")
                                                     .read_text(encoding="utf-8").splitlines()) if m})
    if reads and reads[-1] >= BAR5_LENGTH:
        sys.exit(f"read list reaches 0x{reads[-1]:X}, beyond the 0x{BAR5_LENGTH:X} bytes of BAR5 that mmio.c maps")
    writes = [(offset(maps, ip, name), ip, name, exp, why) for ip, name, exp, why in WRITABLE]
    for off, ip, name, _, _ in writes:
        if off not in reads:
            sys.exit(f"{ip}.{name} is writable but not on the read list: a write must be verifiable")

    out = ["// Generated by gen_regs.py from the vendored amdgpu headers through tools/regcalc. Do not edit.",
           "#pragma once", ""]
    for ip, name in NAMED:
        out.append(f"#define BC250_REG_{ip}_{name[2:]} 0x{offset(maps, ip, name):05X}ul")
    for ip, name in NAMED:
        if offset(maps, ip, name) not in reads:
            sys.exit(f"{ip}.{name} is used by the driver but not on the read list")
    out += ["", "// The tables are for mmio.c alone; everybody else gets the names.", "#ifdef BC250_REGS_WITH_TABLES",
            "", "// Offsets that may be written through the escape, with the experiment that allowed each."]
    out.append(f"#define BC250_MMIO_WRITE_ALLOW_COUNT {len(writes)}")
    out.append("static const unsigned long g_MmioWriteAllow[BC250_MMIO_WRITE_ALLOW_COUNT] = {")
    for off, ip, name, exp, why in sorted(writes):
        out.append(f"    0x{off:05X}ul,   // {ip}.{name[2:]}  {exp}: {why}")
    out += ["};", "", "// Offsets that may be read through the escape: tools/win/bc250rd/reglist.txt. Sorted, unique.",
            f"#define BC250_MMIO_READ_ALLOW_COUNT {len(reads)}",
            "static const unsigned long g_MmioReadAllow[BC250_MMIO_READ_ALLOW_COUNT] = {"]
    out += ["    " + ", ".join(f"0x{o:05X}" for o in reads[i:i + 10]) + "," for i in range(0, len(reads), 10)]
    out += ["};", ""]
    summary = []
    for table, exp, match, until, read_only in SEQUENCES:
        entries = {}
        for _, kind, name, off, _ in accesses(TRACE, match, until=until):
            ip, reg = name.split(".", 1)
            if offset(maps, ip, "mm" + reg) != off:
                sys.exit(f"{name}: the trace has 0x{off:05X}, regcalc says 0x{offset(maps, ip, 'mm' + reg):05X}")
            entries[off] = name
        for ip, reg in read_only:
            entries[offset(maps, ip, reg)] = f"{ip}.{reg[2:]} (read only)"
        if max(entries) >= BAR5_LENGTH:
            sys.exit(f"{table}: 0x{max(entries):X} is beyond BAR5")
        out += [f"// {exp}: what amdgpu wrote on unit A in this step (E03 trace, first {until} s, names matching",
                f"// {match}), plus the registers it only polled. For the kernel command alone.",
                f"#define BC250_MMIO_{table.upper()}_ALLOW_COUNT {len(entries)}",
                f"static const unsigned long g_Mmio{table}Allow[BC250_MMIO_{table.upper()}_ALLOW_COUNT] = {{"]
        out += [f"    0x{off:05X}ul,   // {entries[off]}" for off in sorted(entries)]
        out += ["};", ""]
        summary.append(f"{len(entries)} in the {table} sequence")
    out += ["#endif", ""]
    (HERE / "regs.generated.h").write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"{len(reads)} readable, {len(writes)} writable: " + ", ".join(f"{n[2:]}=0x{o:05X}" for o, _, n, _, _ in writes)
          + "; " + ", ".join(summary))


if __name__ == "__main__":
    main()
