// Writes driver/kmd/umd_caps.c from the unit A caps filler. Not linked into the driver.
#include <stdio.h>
#include <stdint.h>
#include "umd_caps.h"
#include "bc250_caps_test.h"

int main(int argc, char** argv)
{
    uint32_t size = 0;
    const unsigned char* blob;
    FILE* out;
    unsigned i;

    if (argc != 2) {
        fprintf(stderr, "usage: gen_umd_caps <umd_caps.c>\n");
        return 2;
    }
    blob = (const unsigned char*)bc250_unitA_blob(BC250_MUTATE_NONE, &size);
    if (blob == NULL || size != UMD_CAPS_BYTES) {
        fprintf(stderr, "unit A blob is %u bytes, the reader expects %u\n", size, (unsigned)UMD_CAPS_BYTES);
        return 1;
    }
    /* "BC25" little endian, version 3 in the next word. A filler that lost its envelope must not
     * be copied into the driver. */
    if (blob[0] != 0x42 || blob[1] != 0x43 || blob[2] != 0x32 || blob[3] != 0x35 ||
        blob[4] != 3 || blob[5] != 0 || blob[6] != 0 || blob[7] != 0) {
        fprintf(stderr, "unit A blob envelope is not magic BC25 version 3\n");
        return 1;
    }

    out = fopen(argv[1], "wb");
    if (out == NULL) {
        fprintf(stderr, "cannot write %s\n", argv[1]);
        return 1;
    }
    fputs("/* Generated by driver/kmd/test/gen_umd_caps.c from bc250_unitA_blob(BC250_MUTATE_NONE).\n"
          " * Not hand-written. driver/kmd/test/run_umd_caps.ps1 -Generate rewrites this file, and\n"
          " * the same script's compare fails if the filler and these bytes disagree. */\n"
          "#include \"umd_caps.h\"\n"
          "const unsigned char umd_caps_blob[UMD_CAPS_BYTES] = {\n", out);
    for (i = 0; i < size; i++) {
        if (i % 16 == 0) fputs("   ", out);
        fprintf(out, " 0x%02X,", blob[i]);
        if (i % 16 == 15 || i + 1 == size) fputc('\n', out);
    }
    fputs("};\n", out);
    fclose(out);
    printf("wrote %u bytes to %s\n", size, argv[1]);
    return 0;
}
