"""Generated by tools/runcompare/gen_tables.py - do not edit by hand.

Regenerate with `python tools/runcompare/gen_tables.py`; `--check` fails when this
file and the headers have drifted apart.

Sources (paths relative to the NuGet Kits root, resp. to the repository):
    d3dkmddi.h   microsoft.windows.wdk.x64/c/Include/10.0.26100.0/shared/d3dkmddi.h  (Kit 10.0.26100.0)
    ntstatus.h   microsoft.windows.sdk.cpp/c/Include/10.0.26100.0/shared/ntstatus.h  (Kit 10.0.26100.0)
    cfg.h        microsoft.windows.sdk.cpp/c/Include/10.0.26100.0/shared/cfg.h  (Kit 10.0.26100.0)
    bc250kmd.h   driver/kmd/bc250kmd.h  (this repository)
    wddm.c       driver/kmd/wddm.c  (this repository)
"""

HEADER_SOURCES = (
    ('d3dkmddi.h', 'microsoft.windows.wdk.x64/c/Include/10.0.26100.0/shared/d3dkmddi.h', 'Kit 10.0.26100.0'),
    ('ntstatus.h', 'microsoft.windows.sdk.cpp/c/Include/10.0.26100.0/shared/ntstatus.h', 'Kit 10.0.26100.0'),
    ('cfg.h', 'microsoft.windows.sdk.cpp/c/Include/10.0.26100.0/shared/cfg.h', 'Kit 10.0.26100.0'),
    ('bc250kmd.h', 'driver/kmd/bc250kmd.h', 'this repository'),
    ('wddm.c', 'driver/kmd/wddm.c', 'this repository'),
)

QAI_TYPES = {
    0: 'UMDRIVERPRIVATE',
    1: 'DRIVERCAPS',
    2: 'QUERYSEGMENT',
    3: 'RESERVED',
    4: 'QUERYSEGMENT2',
    5: 'QUERYSEGMENT3',
    6: 'NUMPOWERCOMPONENTS',
    7: 'POWERCOMPONENTINFO',
    8: 'PREFERREDGPUNODE',
    9: 'POWERCOMPONENTPSTATEINFO',
    10: 'HISTORYBUFFERPRECISION',
    11: 'QUERYSEGMENT4',
    12: 'SEGMENTMEMORYSTATE',
    13: 'GPUMMUCAPS',
    14: 'PAGETABLELEVELDESC',
    15: 'PHYSICALADAPTERCAPS',
    16: 'DISPLAY_DRIVERCAPS_EXTENSION',
    17: 'INTEGRATED_DISPLAY_DESCRIPTOR',
    18: 'UEFIFRAMEBUFFERRANGES',
    19: 'QUERYCOLORIMETRYOVERRIDES',
    20: 'DISPLAYID_DESCRIPTOR',
    21: 'FRAMEBUFFERSAVESIZE',
    22: 'HARDWARERESERVEDRANGES',
    23: 'INTEGRATED_DISPLAY_DESCRIPTOR2',
    24: 'NODEPERFDATA',
    25: 'ADAPTERPERFDATA',
    26: 'ADAPTERPERFDATA_CAPS',
    27: 'GPUVERSION',
    28: 'DEVICE_TYPE_CAPS',
    29: 'WDDMDEVICECAPS',
    30: 'GPUPCAPS',
    31: 'QUERYTARGETGAMMACAPS',
    33: 'SCANOUT_CAPS',
    34: 'PHYSICAL_MEMORY_CAPS',
    35: 'IOMMU_CAPS',
    36: 'HARDWARERESERVEDRANGES2',
    37: 'NATIVE_FENCE_CAPS',
    38: 'USERMODESUBMISSION_CAPS',
    39: 'DIRTYBITTRACKINGCAPS',
    40: 'DIRTYBITTRACKINGSEGMENTCAPS',
    41: 'SCATTER_RESERVE',
    42: 'QUERYPAGINGBUFFERINFO',
    43: 'QUERYSEGMENTCOUNT',
    44: 'QUERYSEGMENT5',
    45: 'QUERYMMUCOUNT',
    46: 'QUERYMMUS',
    47: '64BITONLYCAPS',
    48: 'PAGINGPROCESSGPUVASIZE',
}

NTSTATUS_NAMES = {
    0x00000000: 'STATUS_SUCCESS',
    0x80000005: 'STATUS_BUFFER_OVERFLOW',
    0xC0000001: 'STATUS_UNSUCCESSFUL',
    0xC0000002: 'STATUS_NOT_IMPLEMENTED',
    0xC0000004: 'STATUS_INFO_LENGTH_MISMATCH',
    0xC000000D: 'STATUS_INVALID_PARAMETER',
    0xC0000010: 'STATUS_INVALID_DEVICE_REQUEST',
    0xC0000017: 'STATUS_NO_MEMORY',
    0xC0000023: 'STATUS_BUFFER_TOO_SMALL',
    0xC000009A: 'STATUS_INSUFFICIENT_RESOURCES',
    0xC00000BB: 'STATUS_NOT_SUPPORTED',
    0xC00000E5: 'STATUS_INTERNAL_ERROR',
    0xC00002B6: 'STATUS_DEVICE_REMOVED',
    0xC01E0003: 'STATUS_GRAPHICS_ADAPTER_WAS_RESET',
    0xC01E0004: 'STATUS_GRAPHICS_INVALID_DRIVER_MODEL',
    0xC01E0009: 'STATUS_GRAPHICS_DRIVER_MISMATCH',
    0xC01E0100: 'STATUS_GRAPHICS_NO_VIDEO_MEMORY',
}

CM_PROB_NAMES = {
    0: 'CM_PROB_NONE',
    1: 'CM_PROB_NOT_CONFIGURED',
    2: 'CM_PROB_DEVLOADER_FAILED',
    3: 'CM_PROB_OUT_OF_MEMORY',
    4: 'CM_PROB_ENTRY_IS_WRONG_TYPE',
    5: 'CM_PROB_LACKED_ARBITRATOR',
    6: 'CM_PROB_BOOT_CONFIG_CONFLICT',
    7: 'CM_PROB_FAILED_FILTER',
    8: 'CM_PROB_DEVLOADER_NOT_FOUND',
    9: 'CM_PROB_INVALID_DATA',
    10: 'CM_PROB_FAILED_START',
    11: 'CM_PROB_LIAR',
    12: 'CM_PROB_NORMAL_CONFLICT',
    13: 'CM_PROB_NOT_VERIFIED',
    14: 'CM_PROB_NEED_RESTART',
    15: 'CM_PROB_REENUMERATION',
    16: 'CM_PROB_PARTIAL_LOG_CONF',
    17: 'CM_PROB_UNKNOWN_RESOURCE',
    18: 'CM_PROB_REINSTALL',
    19: 'CM_PROB_REGISTRY',
    20: 'CM_PROB_VXDLDR',
    21: 'CM_PROB_WILL_BE_REMOVED',
    22: 'CM_PROB_DISABLED',
    23: 'CM_PROB_DEVLOADER_NOT_READY',
    24: 'CM_PROB_DEVICE_NOT_THERE',
    25: 'CM_PROB_MOVED',
    26: 'CM_PROB_TOO_EARLY',
    27: 'CM_PROB_NO_VALID_LOG_CONF',
    28: 'CM_PROB_FAILED_INSTALL',
    29: 'CM_PROB_HARDWARE_DISABLED',
    30: 'CM_PROB_CANT_SHARE_IRQ',
    31: 'CM_PROB_FAILED_ADD',
    32: 'CM_PROB_DISABLED_SERVICE',
    33: 'CM_PROB_TRANSLATION_FAILED',
    34: 'CM_PROB_NO_SOFTCONFIG',
    35: 'CM_PROB_BIOS_TABLE',
    36: 'CM_PROB_IRQ_TRANSLATION_FAILED',
    37: 'CM_PROB_FAILED_DRIVER_ENTRY',
    38: 'CM_PROB_DRIVER_FAILED_PRIOR_UNLOAD',
    39: 'CM_PROB_DRIVER_FAILED_LOAD',
    40: 'CM_PROB_DRIVER_SERVICE_KEY_INVALID',
    41: 'CM_PROB_LEGACY_SERVICE_NO_DEVICES',
    42: 'CM_PROB_DUPLICATE_DEVICE',
    43: 'CM_PROB_FAILED_POST_START',
    44: 'CM_PROB_HALTED',
    45: 'CM_PROB_PHANTOM',
    46: 'CM_PROB_SYSTEM_SHUTDOWN',
    47: 'CM_PROB_HELD_FOR_EJECT',
    48: 'CM_PROB_DRIVER_BLOCKED',
    49: 'CM_PROB_REGISTRY_TOO_LARGE',
    50: 'CM_PROB_SETPROPERTIES_FAILED',
    51: 'CM_PROB_WAITING_ON_DEPENDENCY',
    52: 'CM_PROB_UNSIGNED_DRIVER',
    53: 'CM_PROB_USED_BY_DEBUGGER',
    54: 'CM_PROB_DEVICE_RESET',
    55: 'CM_PROB_CONSOLE_LOCKED',
    56: 'CM_PROB_NEED_CLASS_CONFIG',
    57: 'CM_PROB_GUEST_ASSIGNMENT_FAILED',
}

STAGE_NAMES = {
    0: 'StageNone',
    10: 'StageDriverEntry',
    20: 'StageAddDevice',
    30: 'StageStartEnter',
    31: 'StageStartGuardPassed',
    32: 'StageStartDeviceInfo',
    33: 'StageStartPostDisplayAcquired',
    34: 'StageStartFramebufferMapped',
    35: 'StageStartMmioDone',
    39: 'StageStartDone',
    50: 'StageFirstCommitVidPn',
    60: 'StageFirstPresent',
    61: 'StageFirstPresentDone',
    70: 'StageStopEnter',
    79: 'StageStopDone',
    90: 'StageRefusedByGuard',
    91: 'StageStartFailed',
}

CREATECONTEXT_FLAGS = {
    0: 'SystemContext',
    1: 'GdiContext',
    2: 'VirtualAddressing',
    3: 'SystemProtectedContext',
    4: 'HwQueueSupported',
    5: 'TestContext',
}

CONTEXTINFO_CAPS = {
    0: 'NoPatchingRequired',
    1: 'DriverManagesResidency',
    2: 'UseIoMmu',
}

CREATEDEVICE_FLAGS = {
    0: 'SystemDevice',
    1: 'GdiDevice',
    31: 'DXGK_DEVICE_RESERVED0',
}

CREATEPROCESS_FLAGS = {
    0: 'SystemProcess',
    1: 'GdiProcess',
    2: 'VirtualMachineProcess',
    3: 'VirtualMachineWorkerProcess',
    4: 'SessionIsolatedContainer',
}

# driver/kmd/wddm.c: how many first calls of each DDI reach the guard log.
LOG_CALLS = 8
