#!/usr/bin/env python3
"""gen_facts - the facts graph: check docs/facts/data/*.yaml and generate the Markdown views.

The data files are the only place where facts are written. Everything else is generated:

    docs/facts.md               stable index: the areas, their graphs, how to add a fact
    docs/facts/<area>.md        one table per area, every field of every fact
    docs/facts/current.md       live facts only (not REFUTED, not wholly superseded)
    docs/facts/graphs/<area>.md mermaid graphs of the area's relations

A fact's status is written on its area page (and coloured in the graphs), and no page carries
counts, so adding a fact changes its data file, its area page and current.md, plus the pages
of the facts it has edges to.

Usage:
    gen_facts.py --write        regenerate the views
    gen_facts.py --check        validate the data and fail if any view is stale (the quality gate)
    gen_facts.py next-id        print the next free M number
    gen_facts.py show M123      print one fact as stored

Python standard library only. The data files use a strict subset of YAML (see
docs/facts/README.md) that this script both reads and writes; --check also fails when a
data file is not in the canonical form this script would write.
"""

import argparse
import difflib
import glob
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

STATUSES = ('HYPOTHESIS', 'MEASURED', 'CONFIRMED', 'REFUTED')
EDGE_TYPES = ('uses', 'supports', 'refutes', 'supersedes')
# Text fields of a fact, in file order. claim is required, the rest optional.
TEXT_FIELDS = ('claim', 'status_text', 'detail', 'evidence', 'source', 'why')
FACT_KEYS = ('id', 'status', 'date', 'date_from') + TEXT_FIELDS + ('edges',)
DATE_FROM = ('evidence-path', 'text', 'git')
EDGE_KEYS = ('type', 'to', 'scope', 'auto', 'cue_in', 'cue')
ID_RE = re.compile(r'^([MSR])([1-9]\d*)$')
DATE_RE = re.compile(r'^\d{4}-\d{2}-\d{2}$')
KIND_ORDER = {'M': 0, 'S': 1, 'R': 2}

GENERATED = ('> **GENERATED by `tools/facts/gen_facts.py` from `docs/facts/data/*.yaml` - do not edit by hand.** '
             'Edit the YAML, then run `python tools/facts/gen_facts.py --write`. The gate '
             '`python tools/facts/gen_facts.py --check` (run by `tools/quality/quick.ps1` and the `facts` CI workflow) '
             'fails when this page differs from what the generator writes.')
# Banner of the pages written before 2026-10-03, so that --write still finds and replaces or removes them.
GENERATED_OLD = '<!-- Generated by tools/facts/gen_facts.py from docs/facts/data/.'


def id_key(fid):
    m = ID_RE.match(fid)
    return (KIND_ORDER[m.group(1)], int(m.group(2))) if m else (9, 0)


# ---------------------------------------------------------------- data files

class DataError(Exception):
    pass


def _scalar(text, where):
    text = text.strip()
    if text.startswith('"'):
        try:
            return json.loads(text)
        except json.JSONDecodeError as e:
            raise DataError(f'{where}: bad quoted string ({e})')
    if re.fullmatch(r'-?\d+', text):
        return int(text)
    if text in ('true', 'false'):
        return text == 'true'
    if re.fullmatch(r'[A-Za-z][A-Za-z0-9_-]*', text):
        return text
    raise DataError(f'{where}: value must be a bare word, an integer or a "quoted string": {text[:40]}')


def parse_area_file(path):
    """Read one data file. Raises DataError on anything outside the subset."""
    area = {'facts': []}
    fact = None
    in_edges = False
    for n, line in enumerate(Path(path).read_text(encoding='utf-8').split('\n'), 1):
        where = f'{path}:{n}'
        if not line.strip() or line.startswith('#'):
            continue
        if line.startswith('  - id: '):
            fact = {'id': _scalar(line[8:], where)}
            area['facts'].append(fact)
            in_edges = False
            continue
        if line.startswith('      - '):
            if fact is None or not in_edges:
                raise DataError(f'{where}: edge outside an edges list')
            try:
                edge = json.loads(line[8:])
            except json.JSONDecodeError as e:
                raise DataError(f'{where}: edge is not a JSON object ({e})')
            if not isinstance(edge, dict):
                raise DataError(f'{where}: edge is not a JSON object')
            fact['edges'].append(edge)
            continue
        m = re.match(r'^    ([a-z_]+):(.*)$', line)
        if m and fact is not None:
            key, rest = m.group(1), m.group(2)
            if key in fact:
                raise DataError(f'{where}: duplicate key {key}')
            if key == 'edges':
                if rest.strip() not in ('', '[]'):
                    raise DataError(f'{where}: edges takes a list on the following lines')
                fact['edges'] = []
                in_edges = True
            else:
                fact[key] = _scalar(rest, where)
                in_edges = False
            continue
        m = re.match(r'^([a-z_]+):(.*)$', line)
        if m and fact is None:
            key, rest = m.group(1), m.group(2)
            if key == 'facts':
                if rest.strip():
                    raise DataError(f'{where}: facts takes a list on the following lines')
                continue
            area[key] = _scalar(rest, where)
            continue
        raise DataError(f'{where}: line not in the facts data format')
    return area


def q(text):
    return json.dumps(text, ensure_ascii=False)


def dump_area(area):
    """The canonical text of a data file."""
    out = [
        '# Facts data. Edit here; docs/facts.md and docs/facts/*.md are generated from these files',
        '# by tools/facts/gen_facts.py. Format and workflow: docs/facts/README.md.',
        f'area: {area["area"]}',
        f'order: {area["order"]}',
        f'title: {q(area["title"])}',
        f'description: {q(area["description"])}',
        'facts:',
    ]
    for f in sorted(area['facts'], key=lambda f: id_key(f['id'])):
        out.append(f'  - id: {f["id"]}')
        out.append(f'    status: {f["status"]}')
        for key in ('date', 'date_from') + TEXT_FIELDS:
            if key in f:
                out.append(f'    {key}: {q(f[key])}')
        if f.get('edges'):
            out.append('    edges:')
            for e in sorted(f['edges'], key=lambda e: (EDGE_TYPES.index(e['type']) if e.get('type') in EDGE_TYPES else 9,
                                                       id_key(e.get('to', '')), e.get('cue_in', ''))):
                ordered = {k: e[k] for k in EDGE_KEYS if k in e}
                ordered.update({k: v for k, v in e.items() if k not in ordered})
                out.append('      - ' + json.dumps(ordered, ensure_ascii=False))
    return '\n'.join(out) + '\n'


def load(root):
    data_dir = Path(root) / 'docs' / 'facts' / 'data'
    paths = sorted(data_dir.glob('*.yaml'))
    if not paths:
        raise DataError(f'no data files in {data_dir}')
    areas = [dict(parse_area_file(p), _path=p) for p in paths]
    areas.sort(key=lambda a: (a.get('order', 99), a.get('area', '')))
    return areas


# ---------------------------------------------------------------- validation

LINK_RE = re.compile(r'\]\(([^)\s]+)\)')
EVIDENCE_RE = re.compile(r'(?<![\w/.-])((?:\.\./)?evidence/(?:linux|windows)/[^\s`\'"|,;)\]]+)')


def cited_paths(fact):
    """(path relative to the repo, as written) for every evidence path and relative link in a fact.

    Links in the data are relative to docs/, as they were in the original docs/facts.md."""
    found = []
    for key in TEXT_FIELDS:
        text = fact.get(key) or ''
        for m in LINK_RE.finditer(text):
            target = m.group(1).split('#')[0]
            if not target or re.match(r'^[a-z]+:', target) or target.startswith('/'):
                continue
            found.append((_normalise('docs/' + target), target))
        for m in EVIDENCE_RE.finditer(text):
            raw = m.group(1).rstrip('.:')
            if raw.startswith('../'):
                continue  # a link target, handled above
            found.append((_normalise(raw), raw))
    return found


def _normalise(path):
    parts = []
    for p in path.split('/'):
        if p == '..' and parts:
            parts.pop()
        elif p not in ('', '.'):
            parts.append(p)
    return '/'.join(parts)


def path_exists(root, rel):
    if any(c in rel for c in '*?['):
        return bool(glob.glob(str(Path(root) / rel)))
    return (Path(root) / rel).exists()


def validate(root, areas):
    errors = []
    seen = {}
    keys = set()
    for a in areas:
        p = a['_path']
        for k in ('area', 'order', 'title', 'description'):
            if k not in a:
                errors.append(f'{p.name}: missing {k}')
        if a.get('area') != p.stem:
            errors.append(f'{p.name}: area {a.get("area")!r} does not match the file name')
        if a.get('area') in keys:
            errors.append(f'{p.name}: area {a.get("area")} defined twice')
        keys.add(a.get('area'))
        for f in a['facts']:
            fid = f.get('id')
            where = f'{p.name}: {fid}'
            if not isinstance(fid, str) or not ID_RE.match(fid):
                errors.append(f'{where}: bad id')
                continue
            if fid in seen:
                errors.append(f'{where}: duplicate id (also in {seen[fid]})')
            seen[fid] = p.name
            for k in f:
                if k not in FACT_KEYS:
                    errors.append(f'{where}: unknown key {k}')
            if f.get('status') not in STATUSES:
                errors.append(f'{where}: status {f.get("status")!r} is not one of {", ".join(STATUSES)}')
            st = f.get('status_text')
            if st is not None and leading_status(st) != f.get('status'):
                errors.append(f'{where}: status_text does not start with status {f.get("status")}')
            if not isinstance(f.get('claim'), str) or not f['claim'].strip():
                errors.append(f'{where}: no claim')
            for k in TEXT_FIELDS:
                v = f.get(k)
                if v is not None and (not isinstance(v, str) or '\n' in v):
                    errors.append(f'{where}: {k} must be a one-line string')
            if not isinstance(f.get('date'), str) or not DATE_RE.match(f['date']):
                errors.append(f'{where}: date must be YYYY-MM-DD')
            if 'date_from' in f and f['date_from'] not in DATE_FROM:
                errors.append(f'{where}: date_from must be one of {", ".join(DATE_FROM)}')
            for rel, raw in cited_paths(f):
                if not path_exists(root, rel):
                    errors.append(f'{where}: cited path does not exist: {raw}')
    for a in areas:
        for f in a['facts']:
            for e in f.get('edges', []):
                where = f'{a["_path"].name}: {f.get("id")} edge {e}'
                if e.get('type') not in EDGE_TYPES:
                    errors.append(f'{where}: type must be one of {", ".join(EDGE_TYPES)}')
                if e.get('to') not in seen:
                    errors.append(f'{where}: target does not resolve')
                if e.get('to') == f.get('id'):
                    errors.append(f'{where}: edge to itself')
                if 'scope' in e and e['scope'] != 'partial':
                    errors.append(f'{where}: scope can only be "partial"')
                if 'auto' in e and e['auto'] is not True:
                    errors.append(f'{where}: auto is either true or absent')
                if 'cue_in' in e and e['cue_in'] not in seen:
                    errors.append(f'{where}: cue_in does not resolve')
                for k in e:
                    if k not in EDGE_KEYS:
                        errors.append(f'{where}: unknown edge key {k}')
            if len({(e.get('type'), e.get('to')) for e in f.get('edges', [])}) != len(f.get('edges', [])):
                errors.append(f'{a["_path"].name}: {f.get("id")}: the same edge twice')
    return errors


FACT_ANCHOR_RE = re.compile(r'(?<![\w-])facts/([a-z0-9_-]+)\.md#([msr]\d+)\b')
ANCHOR_SKIP = ('evidence', 'third_party', '.git')


def anchor_links(root, areas):
    """Links elsewhere in the repo to docs/facts/<area>.md#<id> must name the fact's current area.

    Moving a fact to another area changes its page; this catches the links left behind."""
    area_of = {f['id'].lower(): a['area'] for a in areas for f in a['facts']}
    errors = []
    root = Path(root)
    for path in sorted(root.rglob('*.md')):
        rel = path.relative_to(root).as_posix()
        if rel.split('/')[0] in ANCHOR_SKIP or rel.startswith('docs/facts'):
            continue
        for m in FACT_ANCHOR_RE.finditer(path.read_text(encoding='utf-8', errors='replace')):
            area, fid = m.group(1), m.group(2)
            if area_of.get(fid) != area:
                where = area_of.get(fid)
                errors.append(f'{rel}: link to facts/{area}.md#{fid}: '
                              + (f'the fact is in {where}.md' if where else 'no such fact'))
    return errors


def leading_status(text):
    m = re.match(r'^\W*(' + '|'.join(STATUSES) + r')\b', text)
    return m.group(1) if m else None


# ---------------------------------------------------------------- rendering

def cell(text):
    return (text or '').replace('|', '\\|').strip()


def facts_link(text):
    """Rewrite relative link targets for a page one directory below docs/."""
    return LINK_RE.sub(lambda m: '](' + (m.group(1) if re.match(r'^([a-z]+:|#|/)', m.group(1))
                                         else '../' + m.group(1)) + ')', text)


class Graph:
    def __init__(self, areas):
        self.areas = areas
        self.facts = {}
        self.area_of = {}
        for a in areas:
            for f in a['facts']:
                self.facts[f['id']] = f
                self.area_of[f['id']] = a['area']
        self.out = {fid: [] for fid in self.facts}
        self.inc = {fid: [] for fid in self.facts}
        for fid, f in self.facts.items():
            for e in f.get('edges', []):
                self.out[fid].append(e)
                self.inc[e['to']].append(dict(e, to=fid))

    def superseded(self, fid):
        return any(e['type'] == 'supersedes' and e.get('scope') != 'partial' for e in self.inc[fid])

    def live(self, fid):
        return self.facts[fid]['status'] != 'REFUTED' and not self.superseded(fid)

    def anchor(self, fid, from_area=None):
        page = '' if from_area == self.area_of[fid] else f'{self.area_of[fid]}.md'
        return f'[{fid}]({page}#{fid.lower()})'


INCOMING = {'uses': 'used by', 'supports': 'supported by', 'refutes': 'refuted by', 'supersedes': 'superseded by'}


def links_cell(g, fid, area):
    parts = []
    for e in sorted(g.out[fid], key=lambda e: (EDGE_TYPES.index(e['type']), id_key(e['to']))):
        parts.append(f'{e["type"]} {g.anchor(e["to"], area)}' + (' (in part)' if e.get('scope') else ''))
    for e in sorted(g.inc[fid], key=lambda e: (EDGE_TYPES.index(e['type']), id_key(e['to']))):
        parts.append(f'{INCOMING[e["type"]]} {g.anchor(e["to"], area)}' + (' (in part)' if e.get('scope') else ''))
    return '; '.join(parts)


def render_area(g, a):
    key = a['area']
    lines = [GENERATED, '', f'# Facts: {a["title"]}', '',
             a['description'], '',
             f'Source: [`data/{key}.yaml`](data/{key}.yaml). Graphs: [`graphs/{key}.md`](graphs/{key}.md). '
             'All areas: [`../facts.md`](../facts.md). Live facts only: [`current.md`](current.md). '
             'Links in the text are relative to `docs/` in the data and rewritten for this page.', '',
             '| # | Claim | Status | Detail | Evidence | Date | Links |',
             '|---|---|---|---|---|---|---|']
    for f in sorted(a['facts'], key=lambda f: id_key(f['id'])):
        detail = f.get('detail') or f.get('why') or ''
        evidence = f.get('evidence') or f.get('source') or ''
        date = f['date'] + ('' if 'date_from' not in f else ' (from ' + f['date_from'] + ')')
        lines.append('| ' + ' | '.join([
            f'<a id="{f["id"].lower()}"></a>{f["id"]}',
            cell(facts_link(f['claim'])),
            cell(f.get('status_text') or f['status']),
            cell(facts_link(detail)),
            cell(facts_link(evidence)),
            date,
            cell(links_cell(g, f['id'], key)),
        ]) + ' |')
    return '\n'.join(lines) + '\n'


def render_current(g):
    live = [fid for fid in sorted(g.facts, key=id_key) if g.live(fid)]
    lines = [GENERATED, '', '# Facts: live', '',
             'Every fact that is neither `REFUTED` nor wholly superseded (an incoming `supersedes` edge without '
             '`scope: partial`), by ID. The claim only; status, detail, evidence and relations are on the area '
             'page the ID links to. `python tools/facts/gen_facts.py show M123` prints any fact, live or not, '
             'with its area.', '',
             '| # | Area | Claim |', '|---|---|---|']
    for fid in live:
        lines.append(f'| {g.anchor(fid)} | {g.area_of[fid]} | {cell(facts_link(g.facts[fid]["claim"]))} |')
    return '\n'.join(lines) + '\n'


# Mermaid: GitHub renders these, but large graphs become unreadable, so each graph is capped.
GRAPH_NODE_CAP = 60
EDGE_ARROW = {'uses': '-->', 'supports': '==>|supports|', 'refutes': '-.->|refutes|', 'supersedes': '==>|supersedes|'}
CLASSDEFS = [
    '  classDef HYPOTHESIS fill:#fff3c4,stroke:#9a7b00,color:#000',
    '  classDef MEASURED fill:#dbeafe,stroke:#1d4ed8,color:#000',
    '  classDef CONFIRMED fill:#d1fae5,stroke:#047857,color:#000',
    '  classDef REFUTED fill:#fee2e2,stroke:#b91c1c,color:#000',
    '  classDef other stroke-dasharray:4 3',
]


def mermaid(g, area, nodes, edges):
    lines = ['```mermaid', 'flowchart LR']
    for fid in sorted(nodes, key=id_key):
        label = fid if g.area_of[fid] == area else f'{fid}<br/>{g.area_of[fid]}'
        lines.append(f'  {fid}["{label}"]:::{g.facts[fid]["status"]}')
    for src, e in edges:
        lines.append(f'  {src} {EDGE_ARROW[e["type"]]} {e["to"]}')
    lines += CLASSDEFS
    others = [fid for fid in nodes if g.area_of[fid] != area]
    if others:
        lines.append('  class ' + ','.join(sorted(others, key=id_key)) + ' other')
    lines.append('```')
    return lines


def components(nodes, edges):
    adj = {n: set() for n in nodes}
    for src, e in edges:
        adj[src].add(e['to']); adj[e['to']].add(src)
    seen, comps = set(), []
    for n in sorted(nodes, key=id_key):
        if n in seen:
            continue
        stack, comp = [n], []
        seen.add(n)
        while stack:
            x = stack.pop(); comp.append(x)
            for y in adj[x]:
                if y not in seen:
                    seen.add(y); stack.append(y)
        comps.append(comp)
    comps.sort(key=lambda c: (-len(c), id_key(min(c, key=id_key))))
    return comps


def capped_graphs(g, area, types, title):
    """One mermaid block per batch of connected components, each batch at most GRAPH_NODE_CAP nodes."""
    edges = [(src, e) for src in g.facts for e in g.out[src]
             if e['type'] in types and area in (g.area_of[src], g.area_of[e['to']])]
    nodes = {src for src, _ in edges} | {e['to'] for _, e in edges}
    out = [f'## {title}', '']
    if not edges:
        return out + ['None in this area.', '']
    batches, cur = [], []
    for comp in components(nodes, edges):
        if len(comp) > GRAPH_NODE_CAP:
            batches.append(comp)  # a single component above the cap: shown as its own graph
            continue
        if len(cur) + len(comp) > GRAPH_NODE_CAP:
            batches.append(cur); cur = []
        cur = cur + comp
    if cur:
        batches.append(cur)
    for i, batch in enumerate(batches, 1):
        keep = set(batch)
        if len(batches) > 1:
            out += [f'### Part {i}', '']
        out += mermaid(g, area, keep, [(s, e) for s, e in edges if s in keep])
        out.append('')
    return out


def render_graphs(g, a):
    key = a['area']
    lines = [GENERATED, '', f'# Fact graphs: {a["title"]}', '',
             f'Table: [`../{key}.md`](../{key}.md). Colours: status. Edge types: `supersedes`, `refutes` and '
             '`supports` are drawn thick or dashed and labelled, `uses` (one fact cites another) is a plain arrow. '
             'Facts without any relation are not drawn; dashed boxes belong to other areas. Connected facts are drawn '
             f'in parts of at most {GRAPH_NODE_CAP} (a larger single cluster keeps its own part).', '']
    lines += capped_graphs(g, key, ('supports', 'refutes', 'supersedes'), 'Corrections and support')
    lines += capped_graphs(g, key, ('uses',), 'References')
    return '\n'.join(lines) + '\n'


def render_index(areas):
    """The index. It depends only on the area headers, so adding or changing a fact leaves it alone."""
    lines = [GENERATED, '', '# Facts', '',
             'The only list of established facts in this project. Rules and statuses: '
             '[`01-evidence-rules.md`](01-evidence-rules.md). Nothing is `MEASURED` or `CONFIRMED` without hardware '
             'evidence in `evidence/`.', '',
             'Facts are kept as a graph in [`facts/data/`](facts/data/), one YAML file per area. This page and every '
             'page under [`facts/`](facts/) are generated from it; format, edges and area borders: '
             '[`facts/README.md`](facts/README.md).', '',
             '## Areas', '',
             '| Area | What belongs there | Graphs |', '|---|---|---|']
    for a in areas:
        lines.append(f'| [{a["title"]}](facts/{a["area"]}.md) | {cell(a["description"])} | '
                     f'[graphs](facts/graphs/{a["area"]}.md) |')
    lines += ['', 'Live facts only (not refuted, not superseded), one line each: '
              '[`facts/current.md`](facts/current.md).', '',
              '## Adding a fact', '',
              '1. `python tools/facts/gen_facts.py next-id` prints the next free ID.',
              '2. Append the fact, with its edges to the facts it uses, supports, refutes or supersedes, to its '
              'area file in [`facts/data/`](facts/data/). That is the only file you edit.',
              '3. `python tools/facts/gen_facts.py --write` regenerates the pages; commit them with the data file. '
              '`--check` (in `tools/quality/quick.ps1` and CI) fails when this step was forgotten.', '',
              'Correct a fact in place and link the newer one to it (`supersedes` or `refutes`); never append a '
              'second version. IDs are never reused or renumbered.']
    return '\n'.join(lines) + '\n'


def render_all(root, areas):
    g = Graph(areas)
    docs = Path(root) / 'docs'
    files = {docs / 'facts.md': render_index(areas),
             docs / 'facts' / 'current.md': render_current(g)}
    for a in areas:
        files[docs / 'facts' / f'{a["area"]}.md'] = render_area(g, a)
        files[docs / 'facts' / 'graphs' / f'{a["area"]}.md'] = render_graphs(g, a)
    for a in areas:
        files[a['_path']] = dump_area(a)
    return files


def generated_set(root):
    """Generated files currently on disk (to catch a stale page of an area that no longer exists)."""
    docs = Path(root) / 'docs' / 'facts'
    found = set(docs.glob('*.md')) | set((docs / 'graphs').glob('*.md'))
    return {p for p in found if p.read_text(encoding='utf-8').startswith((GENERATED, GENERATED_OLD))}


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--root', default=str(REPO), help='repository root (default: this checkout)')
    ap.add_argument('--write', action='store_true', help='regenerate the views and normalise the data files')
    ap.add_argument('--check', action='store_true', help='validate; fail if a view or data file differs')
    ap.add_argument('command', nargs='*', help='next-id | show ID')
    args = ap.parse_args(argv)
    root = Path(args.root)
    try:
        areas = load(root)
    except DataError as e:
        print(f'FAIL data: {e}')
        return 1
    errors = validate(root, areas) + anchor_links(root, areas)
    if args.command:
        facts = {f['id']: f for a in areas for f in a['facts']}
        if args.command[0] == 'next-id':
            print('M' + str(max(int(i[1:]) for i in facts if i.startswith('M')) + 1))
            return 0
        if args.command[0] == 'show' and len(args.command) == 2 and args.command[1] in facts:
            fid = args.command[1]
            area = next(a['area'] for a in areas if any(f['id'] == fid for f in a['facts']))
            print(f'{fid}: docs/facts/data/{area}.yaml, page docs/facts/{area}.md#{fid.lower()}')
            print(json.dumps(facts[fid], ensure_ascii=False, indent=2))
            return 0
        ap.error('unknown command')
    for e in errors:
        print(f'FAIL {e}')
    if errors:
        print(f'{len(errors)} error(s)')
        return 1
    files = render_all(root, areas)
    if args.write:
        for path, text in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.exists() or path.read_text(encoding='utf-8') != text:
                path.write_text(text, encoding='utf-8', newline='\n')
                print(f'wrote {path.relative_to(root)}')
        for path in generated_set(root) - set(files):
            path.unlink()
            print(f'removed {path.relative_to(root)}')
        return 0
    stale = []
    for path, text in files.items():
        current = path.read_text(encoding='utf-8') if path.exists() else ''
        if current != text:
            stale.append(path)
            diff = list(difflib.unified_diff(current.split('\n'), text.split('\n'), lineterm='', n=0))
            print(f'FAIL stale: {path.relative_to(root)} ({len(diff)} diff lines); first: '
                  + (next((d for d in diff[2:] if d[:1] in '+-'), '')[:160]))
    for path in generated_set(root) - set(files):
        stale.append(path)
        print(f'FAIL stale: {path.relative_to(root)} is generated but no longer produced')
    if stale:
        print(f'{len(stale)} file(s) out of date: run python tools/facts/gen_facts.py --write')
        return 1
    n = sum(len(a['facts']) for a in areas)
    nedges = sum(len(f.get('edges', [])) for a in areas for f in a['facts'])
    print(f'PASS facts: {n} facts in {len(areas)} areas, {nedges} edges, views up to date')
    return 0


if __name__ == '__main__':
    sys.exit(main())
