#!/usr/bin/env python3
"""Generate allowlist.h and reglist.txt for bc250rd from the Linux reference sweep (experiment E03).

Only registers that were read on unit A under Linux, before any driver, without harm are allowed:
all GC registers of run 1 and the non-GC registers of run 2 (which already honours the conservative
skip list). A read of the wrong BAR5 address can hang this SoC (facts M16), so the kernel driver
refuses every offset that is not in this table.

Run:  python tools/win/bc250rd/gen_allowlist.py
"""

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
EVID = HERE.parents[2] / "evidence" / "linux" / "2026-09-21-E03-init-trace"
LINE = re.compile(r"^([A-Z0-9]+)\.(\S+) (0x[0-9a-f]+) ([0-9A-F]{8})$")


def good_reads(path, only_ip=None):
    for line in path.read_text(encoding="utf-8").splitlines():
        m = LINE.match(line)
        if m and (only_ip is None or m.group(1) == only_ip):
            yield m.group(1), m.group(2), int(m.group(3), 16)


def main():
    regs = list(good_reads(EVID / "sweep-before-run1-GC-complete-then-hang.log", only_ip="GC"))
    regs += [r for r in good_reads(EVID / "sweep-before-run2-nonGC.log") if r[0] != "GC"]
    offsets = sorted({off for _, _, off in regs})
    rows = [", ".join(f"0x{o:05X}" for o in offsets[i:i + 10]) for i in range(0, len(offsets), 10)]
    (HERE / "driver" / "allowlist.h").write_text(
        "// Generated by gen_allowlist.py from evidence/linux/2026-09-21-E03-init-trace. Do not edit.\n"
        "// BAR5 byte offsets that were read on unit A under Linux without harm. Sorted, unique.\n"
        f"#define BC250RD_ALLOW_COUNT {len(offsets)}\n"
        "static const unsigned long g_Allow[BC250RD_ALLOW_COUNT] = {\n    "
        + ",\n    ".join(rows) + "\n};\n", encoding="utf-8", newline="\n")
    (HERE / "reglist.txt").write_text(
        "".join(f"{ip}.{name} 0x{off:05x}\n" for ip, name, off in regs), encoding="utf-8", newline="\n")
    print(f"{len(regs)} registers, {len(offsets)} unique offsets")


if __name__ == "__main__":
    main()
