// SPDX-License-Identifier: MIT
#include "ddi-raster.h"
namespace bc250::umd {
static_assert(unsigned(D3D10_DDI_PRIMITIVE_TOPOLOGY_UNDEFINED)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_UNDEFINED));
static_assert(unsigned(D3D10_DDI_PRIMITIVE_TOPOLOGY_POINTLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_POINTLIST));
static_assert(unsigned(D3D10_DDI_PRIMITIVE_TOPOLOGY_LINELIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_LINELIST));
static_assert(unsigned(D3D10_DDI_PRIMITIVE_TOPOLOGY_LINESTRIP)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP));
static_assert(unsigned(D3D10_DDI_PRIMITIVE_TOPOLOGY_TRIANGLELIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST));
static_assert(unsigned(D3D10_DDI_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP));
static_assert(unsigned(D3D10_DDI_PRIMITIVE_TOPOLOGY_LINELIST_ADJ)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_LINELIST_ADJ));
static_assert(unsigned(D3D10_DDI_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ));
static_assert(unsigned(D3D10_DDI_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ));
static_assert(unsigned(D3D10_DDI_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST));
static_assert(unsigned(D3D11_DDI_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST)==unsigned(D3D11_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST));
HRESULT convert_viewports(UINT count,UINT clear,const D3D10_DDI_VIEWPORT *input,Viewports &out) {
    if (count>out.size() || clear>out.size()-count || (count && !input)) return E_INVALIDARG;
    Viewports result{};
    for (UINT i=0;i<count;++i) {
        const auto &v=input[i];
        result[i]={v.TopLeftX,v.TopLeftY,v.Width,v.Height,v.MinDepth,v.MaxDepth};
    }
    out=result; return S_OK;
}
bool valid_topology(D3D10_DDI_PRIMITIVE_TOPOLOGY t) {
    switch (t) {
    case D3D10_DDI_PRIMITIVE_TOPOLOGY_UNDEFINED:
    case D3D10_DDI_PRIMITIVE_TOPOLOGY_POINTLIST:
    case D3D10_DDI_PRIMITIVE_TOPOLOGY_LINELIST:
    case D3D10_DDI_PRIMITIVE_TOPOLOGY_LINESTRIP:
    case D3D10_DDI_PRIMITIVE_TOPOLOGY_TRIANGLELIST:
    case D3D10_DDI_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP:
    case D3D10_DDI_PRIMITIVE_TOPOLOGY_LINELIST_ADJ:
    case D3D10_DDI_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ:
    case D3D10_DDI_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ:
    case D3D10_DDI_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ: return true;
    default: return t>=D3D11_DDI_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST &&
        t<=D3D11_DDI_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST;
    }
}
namespace {
void APIENTRY viewports(D3D10DDI_HDEVICE h,UINT count,UINT clear,const D3D10_DDI_VIEWPORT *input) {
    enter_context(h,[&](ID3D11DeviceContext4 &context) {
        Viewports converted;
        HRESULT hr=convert_viewports(count,clear,input,converted);
        if (FAILED(hr)) { report_ddi_error(*static_cast<DdiDeviceHandle *>(h.pDrvPrivate)->owner,hr); return; }
        // D3D11 COM sets the complete active array and unbinds omitted slots.
        context.RSSetViewports(count,count ? converted.data() : nullptr);
    });
}
void APIENTRY scissors(D3D10DDI_HDEVICE h,UINT count,UINT clear,const D3D10_DDI_RECT *input) {
    enter_context(h,[&](ID3D11DeviceContext4 &context) {
        constexpr UINT limit=D3D11_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE;
        if (count>limit || clear>limit-count || (count && !input)) {
            report_ddi_error(*static_cast<DdiDeviceHandle *>(h.pDrvPrivate)->owner,D3DDDIERR_DEVICEREMOVED); return;
        }
        context.RSSetScissorRects(count,input);
    });
}
void APIENTRY topology(D3D10DDI_HDEVICE h,D3D10_DDI_PRIMITIVE_TOPOLOGY value) {
    enter_context(h,[&](ID3D11DeviceContext4 &context) {
        if (!valid_topology(value)) {
            report_ddi_error(*static_cast<DdiDeviceHandle *>(h.pDrvPrivate)->owner,D3DDDIERR_DEVICEREMOVED); return;
        }
        context.IASetPrimitiveTopology(static_cast<D3D11_PRIMITIVE_TOPOLOGY>(value));
    });
}
}
void install_raster_ddi(D3D11_1DDI_DEVICEFUNCS &table) {
    table.pfnSetViewports=viewports;
    table.pfnSetScissorRects=scissors;
    table.pfnIaSetTopology=topology;
}
}
