#include <stdio.h>
#include "bc250_clock.h"
#include "bc250_cpu.h"
#include "bc250_dpm.h"
#include "bc250_fan.h"
int main(void) {
    unsigned i,j;
    struct bc250_fan_curve curve;
printf("BC250_CLOCK_MIN_MHZ=%llu\n",(unsigned long long)(BC250_CLOCK_MIN_MHZ));
printf("BC250_CLOCK_FLOOR_MHZ=%llu\n",(unsigned long long)(BC250_CLOCK_FLOOR_MHZ));
printf("BC250_CLOCK_CEILING_MHZ=%llu\n",(unsigned long long)(BC250_CLOCK_CEILING_MHZ));
printf("BC250_CLOCK_STEP_MHZ=%llu\n",(unsigned long long)(BC250_CLOCK_STEP_MHZ));
printf("BC250_CLOCK_LEVELS=%llu\n",(unsigned long long)(BC250_CLOCK_LEVELS));
printf("BC250_CLOCK_FLOOR_MV=%llu\n",(unsigned long long)(BC250_CLOCK_FLOOR_MV));
printf("BC250_CLOCK_CEILING_MV=%llu\n",(unsigned long long)(BC250_CLOCK_CEILING_MV));
printf("BC250_CLOCK_HOT_MC=%llu\n",(unsigned long long)(BC250_CLOCK_HOT_MC));
printf("BC250_CURVE_UNDERVOLT_MV=%llu\n",(unsigned long long)(BC250_CURVE_UNDERVOLT_MV));
printf("BC250_CPU_MIN_MHZ=%llu\n",(unsigned long long)(BC250_CPU_MIN_MHZ));
printf("BC250_CPU_MAX_MHZ=%llu\n",(unsigned long long)(BC250_CPU_MAX_MHZ));
printf("BC250_CPU_MAX_MHZ_LAB=%llu\n",(unsigned long long)(BC250_CPU_MAX_MHZ_LAB));
printf("BC250_CPU_LAB_MIN_UV_STEPS=%llu\n",(unsigned long long)(BC250_CPU_LAB_MIN_UV_STEPS));
printf("BC250_CPU_UV_MAX_STEPS=%llu\n",(unsigned long long)(BC250_CPU_UV_MAX_STEPS));
printf("BC250_CPU_TEMP_MIN_C=%llu\n",(unsigned long long)(BC250_CPU_TEMP_MIN_C));
printf("BC250_CPU_TEMP_MAX_C=%llu\n",(unsigned long long)(BC250_CPU_TEMP_MAX_C));
printf("BC250_CPU_REFUSE_MV=%llu\n",(unsigned long long)(BC250_CPU_REFUSE_MV));
printf("BC250_CPU_PLAUSIBLE_MIN_MV=%llu\n",(unsigned long long)(BC250_CPU_PLAUSIBLE_MIN_MV));
printf("BC250_CPU_PLAUSIBLE_MAX_MV=%llu\n",(unsigned long long)(BC250_CPU_PLAUSIBLE_MAX_MV));
printf("BC250_CPU_STRETCH_MHZ=%llu\n",(unsigned long long)(BC250_CPU_STRETCH_MHZ));
printf("BC250_CPU_GPU_BUSY_PERMILLE=%llu\n",(unsigned long long)(BC250_CPU_GPU_BUSY_PERMILLE));
printf("BC250_CPU_MASK_STOCK=%llu\n",(unsigned long long)(BC250_CPU_MASK_STOCK));
printf("BC250_CPU_MASK_FULL=%llu\n",(unsigned long long)(BC250_CPU_MASK_FULL));
printf("BC250_FAN_POINTS_MIN=%llu\n",(unsigned long long)(BC250_FAN_POINTS_MIN));
printf("BC250_FAN_POINTS_MAX=%llu\n",(unsigned long long)(BC250_FAN_POINTS_MAX));
printf("BC250_FAN_FLOOR_PCT=%llu\n",(unsigned long long)(BC250_FAN_FLOOR_PCT));
printf("BC250_FAN_FULL_PCT=%llu\n",(unsigned long long)(BC250_FAN_FULL_PCT));
printf("BC250_FAN_TEMP_MIN_C=%llu\n",(unsigned long long)(BC250_FAN_TEMP_MIN_C));
printf("BC250_FAN_TEMP_MAX_C=%llu\n",(unsigned long long)(BC250_FAN_TEMP_MAX_C));
printf("BC250_FAN_EMERGENCY_ON_MC=%llu\n",(unsigned long long)(BC250_FAN_EMERGENCY_ON_MC));
printf("BC250_FAN_EMERGENCY_OFF_MC=%llu\n",(unsigned long long)(BC250_FAN_EMERGENCY_OFF_MC));
printf("BC250_FAN_EMERGENCY_HOLD_MS=%llu\n",(unsigned long long)(BC250_FAN_EMERGENCY_HOLD_MS));
printf("BC250_FAN_BOOST_BUSY_PERMILLE=%llu\n",(unsigned long long)(BC250_FAN_BOOST_BUSY_PERMILLE));
printf("BC250_FAN_BOOST_MHZ=%llu\n",(unsigned long long)(BC250_FAN_BOOST_MHZ));
printf("BC250_FAN_BOOST_POWER_MW=%llu\n",(unsigned long long)(BC250_FAN_BOOST_POWER_MW));
printf("BC250_FAN_BOOST_RISE_MS=%llu\n",(unsigned long long)(BC250_FAN_BOOST_RISE_MS));
printf("BC250_FAN_BOOST_RISE_MC=%llu\n",(unsigned long long)(BC250_FAN_BOOST_RISE_MC));
printf("BC250_FAN_BOOST_ARM_MS=%llu\n",(unsigned long long)(BC250_FAN_BOOST_ARM_MS));
printf("BC250_FAN_BOOST_LOAD_MAX_MS=%llu\n",(unsigned long long)(BC250_FAN_BOOST_LOAD_MAX_MS));
printf("BC250_FAN_BOOST_STEP_MAX_MS=%llu\n",(unsigned long long)(BC250_FAN_BOOST_STEP_MAX_MS));
printf("BC250_FAN_BOOST_HOLD_MS=%llu\n",(unsigned long long)(BC250_FAN_BOOST_HOLD_MS));
printf("BC250_FAN_LEASE_MIN_MS=%llu\n",(unsigned long long)(BC250_FAN_LEASE_MIN_MS));
printf("BC250_FAN_LEASE_MAX_MS=%llu\n",(unsigned long long)(BC250_FAN_LEASE_MAX_MS));
printf("BC250_FAN_LEASE_DEFAULT_MS=%llu\n",(unsigned long long)(BC250_FAN_LEASE_DEFAULT_MS));
printf("BC250_DPM_FLOOR_LEVEL=%llu\n",(unsigned long long)(BC250_DPM_FLOOR_LEVEL));
printf("BC250_DPM_THERMAL_FLOOR_LEVEL=%llu\n",(unsigned long long)(BC250_DPM_THERMAL_FLOOR_LEVEL));
printf("BC250_DPM_IDLE_LEVEL=%llu\n",(unsigned long long)(BC250_DPM_IDLE_LEVEL));
printf("BC250_DPM_HOT_MC=%llu\n",(unsigned long long)(BC250_DPM_HOT_MC));
printf("BC250_DPM_WARM_MC=%llu\n",(unsigned long long)(BC250_DPM_WARM_MC));
printf("BC250_DPM_HOT_STEP_MS=%llu\n",(unsigned long long)(BC250_DPM_HOT_STEP_MS));
printf("BC250_DPM_DEFAULT_MAX_MHZ=%llu\n",(unsigned long long)(BC250_DPM_DEFAULT_MAX_MHZ));
printf("BC250_DPM_MODE_FIXED=%llu\n",(unsigned long long)(BC250_DPM_MODE_FIXED));
printf("BC250_DPM_MODE_DPM=%llu\n",(unsigned long long)(BC250_DPM_MODE_DPM));
printf("BC250_DPM_DEFAULT_MODE=%llu\n",(unsigned long long)(BC250_DPM_DEFAULT_MODE));
printf("BC250_DPM_TOP_LEVEL=%llu\n",(unsigned long long)(BC250_DPM_TOP_LEVEL));
printf("BC250_DPM_ENCODED_TAG=%llu\n",(unsigned long long)(BC250_DPM_ENCODED_TAG));
printf("BC250_DPM_UP_PERMILLE=%llu\n",(unsigned long long)(BC250_DPM_UP_PERMILLE));
printf("BC250_DPM_TARGET_PERMILLE=%llu\n",(unsigned long long)(BC250_DPM_TARGET_PERMILLE));
printf("BC250_DPM_DOWN_PERMILLE=%llu\n",(unsigned long long)(BC250_DPM_DOWN_PERMILLE));
printf("BC250_DPM_DOWN_HOLD_MS=%llu\n",(unsigned long long)(BC250_DPM_DOWN_HOLD_MS));
printf("BC250_DPM_RAMP_KNEE_MC=%llu\n",(unsigned long long)(BC250_DPM_RAMP_KNEE_MC));
printf("BC250_DPM_RAMP_MIN_MS=%llu\n",(unsigned long long)(BC250_DPM_RAMP_MIN_MS));
printf("BC250_DPM_RAMP_MAX_MS=%llu\n",(unsigned long long)(BC250_DPM_RAMP_MAX_MS));
printf("BC250_DPM_CRITICAL_MC=%llu\n",(unsigned long long)(BC250_DPM_CRITICAL_MC));
printf("BC250_DPM_RELEASE_MC=%llu\n",(unsigned long long)(BC250_DPM_RELEASE_MC));
printf("BC250_DPM_RELEASE_STEP_MS=%llu\n",(unsigned long long)(BC250_DPM_RELEASE_STEP_MS));
printf("BC250_DPM_SOFT_DELTA_MC=%llu\n",(unsigned long long)(BC250_DPM_SOFT_DELTA_MC));
printf("BC250_DPM_SOFT_STEP_MS=%llu\n",(unsigned long long)(BC250_DPM_SOFT_STEP_MS));
printf("BC250_DPM_ZONE_DELTA_MC=%llu\n",(unsigned long long)(BC250_DPM_ZONE_DELTA_MC));
printf("BC250_DPM_ZONE_STEP_MS=%llu\n",(unsigned long long)(BC250_DPM_ZONE_STEP_MS));
printf("BC250_DPM_ZONE_LEAD_MS=%llu\n",(unsigned long long)(BC250_DPM_ZONE_LEAD_MS));
printf("BC250_DPM_ZONE_SLOPE_MS=%llu\n",(unsigned long long)(BC250_DPM_ZONE_SLOPE_MS));
printf("BC250_DPM_ZONE_SLOPE_SLOTS=%llu\n",(unsigned long long)(BC250_DPM_ZONE_SLOPE_SLOTS));
printf("BC250_DPM_ZONE_SLOPE_SLOT_MS=%llu\n",(unsigned long long)(BC250_DPM_ZONE_SLOPE_SLOT_MS));
printf("BC250_DPM_ZONE_SLOPE_MAX_SPAN_MS=%llu\n",(unsigned long long)(BC250_DPM_ZONE_SLOPE_MAX_SPAN_MS));
printf("BC250_DPM_ZONE_SLOPE_MIN_MC=%llu\n",(unsigned long long)(BC250_DPM_ZONE_SLOPE_MIN_MC));
printf("BC250_DPM_ZONE_LEAD_MAX_MC=%llu\n",(unsigned long long)(BC250_DPM_ZONE_LEAD_MAX_MC));
printf("BC250_DPM_ZONE_WORK_PERMILLE=%llu\n",(unsigned long long)(BC250_DPM_ZONE_WORK_PERMILLE));
printf("BC250_DPM_ZONE_QUIET_MS=%llu\n",(unsigned long long)(BC250_DPM_ZONE_QUIET_MS));
printf("BC250_DPM_IDLE_MHZ=%llu\n",(unsigned long long)(BC250_DPM_IDLE_MHZ));
printf("BC250_DPM_IDLE_HOLD_MS=%llu\n",(unsigned long long)(BC250_DPM_IDLE_HOLD_MS));
printf("BC250_DPM_IDLE_BUSY_PERMILLE=%llu\n",(unsigned long long)(BC250_DPM_IDLE_BUSY_PERMILLE));
printf("BC250_DPM_IDLE_MIN_HOLD_MS=%llu\n",(unsigned long long)(BC250_DPM_IDLE_MIN_HOLD_MS));
printf("BC250_DPM_IDLE_MAX_HOLD_MS=%llu\n",(unsigned long long)(BC250_DPM_IDLE_MAX_HOLD_MS));
printf("BC250_DPM_IDLE_MAX_BUSY_PERMILLE=%llu\n",(unsigned long long)(BC250_DPM_IDLE_MAX_BUSY_PERMILLE));
printf("BC250_DPM_IDLE_EXIT_PERMILLE=%llu\n",(unsigned long long)(BC250_DPM_IDLE_EXIT_PERMILLE));
printf("BC250_DPM_IDLE_LEAVE_PERMILLE=%llu\n",(unsigned long long)(BC250_DPM_IDLE_LEAVE_PERMILLE));
printf("BC250_DPM_IDLE_MIN_LEAVE_PERMILLE=%llu\n",(unsigned long long)(BC250_DPM_IDLE_MIN_LEAVE_PERMILLE));
printf("BC250_DPM_IDLE_MAX_LEAVE_PERMILLE=%llu\n",(unsigned long long)(BC250_DPM_IDLE_MAX_LEAVE_PERMILLE));
printf("BC250_DPM_MAX_DT_MS=%llu\n",(unsigned long long)(BC250_DPM_MAX_DT_MS));
printf("BC250_DPM_CAP_MS_MAX=%llu\n",(unsigned long long)(BC250_DPM_CAP_MS_MAX));
printf("BC250_DPM_HW_SAMPLE_US=%llu\n",(unsigned long long)(BC250_DPM_HW_SAMPLE_US));
printf("BC250_DPM_HW_MIN_SAMPLES=%llu\n",(unsigned long long)(BC250_DPM_HW_MIN_SAMPLES));
printf("BC250_DPM_TUNE_MIN_PERMILLE=%llu\n",(unsigned long long)(BC250_DPM_TUNE_MIN_PERMILLE));
printf("BC250_DPM_TUNE_MAX_PERMILLE=%llu\n",(unsigned long long)(BC250_DPM_TUNE_MAX_PERMILLE));
printf("BC250_DPM_TUNE_MIN_HOLD_MS=%llu\n",(unsigned long long)(BC250_DPM_TUNE_MIN_HOLD_MS));
printf("BC250_DPM_TUNE_MAX_HOLD_MS=%llu\n",(unsigned long long)(BC250_DPM_TUNE_MAX_HOLD_MS));
printf("BC250_DPM_TUNE_MIN_HOT_STEP_MS=%llu\n",(unsigned long long)(BC250_DPM_TUNE_MIN_HOT_STEP_MS));
printf("BC250_DPM_TUNE_MAX_HOT_STEP_MS=%llu\n",(unsigned long long)(BC250_DPM_TUNE_MAX_HOT_STEP_MS));
printf("BC250_DPM_TUNE_MIN_SOFT_DELTA_MC=%llu\n",(unsigned long long)(BC250_DPM_TUNE_MIN_SOFT_DELTA_MC));
printf("BC250_DPM_TUNE_MAX_SOFT_DELTA_MC=%llu\n",(unsigned long long)(BC250_DPM_TUNE_MAX_SOFT_DELTA_MC));
printf("BC250_DPM_TUNE_MIN_SOFT_STEP_MS=%llu\n",(unsigned long long)(BC250_DPM_TUNE_MIN_SOFT_STEP_MS));
printf("BC250_DPM_TUNE_MAX_SOFT_STEP_MS=%llu\n",(unsigned long long)(BC250_DPM_TUNE_MAX_SOFT_STEP_MS));
printf("BC250_DPM_TUNE_MIN_ZONE_DELTA_MC=%llu\n",(unsigned long long)(BC250_DPM_TUNE_MIN_ZONE_DELTA_MC));
printf("BC250_DPM_TUNE_MAX_ZONE_DELTA_MC=%llu\n",(unsigned long long)(BC250_DPM_TUNE_MAX_ZONE_DELTA_MC));
printf("BC250_DPM_TUNE_MIN_ZONE_STEP_MS=%llu\n",(unsigned long long)(BC250_DPM_TUNE_MIN_ZONE_STEP_MS));
printf("BC250_DPM_TUNE_MAX_ZONE_STEP_MS=%llu\n",(unsigned long long)(BC250_DPM_TUNE_MAX_ZONE_STEP_MS));
printf("BC250_DPM_TUNE_MAX_ZONE_LEAD_MS=%llu\n",(unsigned long long)(BC250_DPM_TUNE_MAX_ZONE_LEAD_MS));
printf("BC250_DPM_CURVE_TRIAL_MS=%llu\n",(unsigned long long)(BC250_DPM_CURVE_TRIAL_MS));
printf("BC250_DPM_CURVE_TRIAL_MIN_MS=%llu\n",(unsigned long long)(BC250_DPM_CURVE_TRIAL_MIN_MS));
printf("BC250_DPM_CURVE_TRIAL_MAX_MS=%llu\n",(unsigned long long)(BC250_DPM_CURVE_TRIAL_MAX_MS));
printf("BC250_DPM_CURVE_KEEP_MIN_MS=%llu\n",(unsigned long long)(BC250_DPM_CURVE_KEEP_MIN_MS));
printf("BC250_DPM_SESSION_CLEAR_MS=%llu\n",(unsigned long long)(BC250_DPM_SESSION_CLEAR_MS));
    for(i=0;i<BC250_CLOCK_LEVELS;++i)
        printf("GPU %u %u %u\n",bc250_clock_points[i].mhz,bc250_clock_points[i].mv,bc250_clock_points[i].vid);
    for(i=0;i<BC250_FAN_PROFILE_COUNT;++i) {
        int result=bc250_fan_profile_curve(i,&curve);
        printf("FAN %u %d\n",i,result);
        if(result!=BC250_FAN_ERROR_OK)continue;
        printf("COUNT %u\n",curve.points);
        for(j=0;j<curve.points;++j)printf("POINT %u %u\n",curve.p[j].c,curve.p[j].pct);
    }
    return 0;
}