"""Extract complete unchanged AMD mailbox functions and named register offsets."""
from pathlib import Path
import re, sys
repo=Path(__file__).resolve().parents[3]
s=(repo/'driver/amdgpu-import/reference/smu_cmn.c').read_text()
license=s[:s.index('*/')+2]
names=['static void smu_cmn_read_arg(', 'static int __smu_cmn_reg2errno(',
       'static void __smu_cmn_send_msg(', 'int smu_cmn_send_msg_without_waiting(',
       'int smu_cmn_wait_for_response(']
parts=[]
for name in names:
    start=s.index(name); end=s.index('\n}\n',start)+3
    parts.append(s[start:end])
constants='\n'.join(re.findall(r'^#define SMU_RESP_.*$',s,re.M))
result=license+'\n// Generated by driver/shim/test/extract_smu.py; do not hand-edit.\n'+constants+'\n\n'+'\n'.join(parts)
sys.path.insert(0,str(repo/'tools/regcalc'))
from regcalc import RegMap, HDR_DIR
rm=RegMap(ip='MP1',reg_header=HDR_DIR/'mp_11_0_8_offset.h')
registers='// Generated via regcalc from cyan_skillfish_ip_offset.h and mp_11_0_8_offset.h.\n#pragma once\n'
for suffix in (66,82,90):
    name=f'mmMP1_SMN_C2PMSG_{suffix}'
    registers+=f'#define BC250_SMU_{name} 0x{rm.byte_offset(name):05X}u\n'
thermal=RegMap(ip='THM',reg_header=HDR_DIR/'thm_10_0_offset.h')
registers+=f'#define BC250_SMU_mmTHM_TCON_CUR_TMP 0x{thermal.byte_offset("mmTHM_TCON_CUR_TMP"):05X}u\n'
for path,text in [(repo/'driver/amdgpu-import/smu_mailbox.inc',result),(repo/'driver/shim/generated/smu_registers.h',registers)]:
    if '--check' in sys.argv:
        assert path.read_text()==text, str(path)+' drift'
    else:path.write_text(text)
print('AMD mailbox bodies and MP1 offsets verified' if '--check' in sys.argv else 'AMD mailbox bodies and MP1 offsets generated')
