"""Extract unchanged AMD clock policy; --check verifies the committed excerpt."""
import re
import sys
from pathlib import Path
repo = Path(__file__).resolve().parents[3]
source = repo / "driver/amdgpu-import/reference/cyan_skillfish_ppt.c"
target = repo / "driver/amdgpu-import/cyan_skillfish_clock.inc"
s = source.read_text(encoding="utf-8")
license = s[:s.index("*/") + 2]
constants = "\n".join(re.findall(r"^#define CYAN_SKILLFISH_(?:SCLK|VDDC)_.*$", s, re.M))
start = s.index("static int cyan_skillfish_od_edit_dpm_table(")
end = s.index("\nstatic int cyan_skillfish_get_dpm_ultimate_freq", start)
result = license + "\n// Generated by driver/shim/test/extract_clock.py; do not hand-edit.\n" + constants + "\n\n" + s[start:end].rstrip() + "\n"
if "--check" in sys.argv:
    assert target.read_text(encoding="utf-8") == result, "AMD clock excerpt drift"
    print("AMD clock constants and complete function match pinned source")
else:
    target.write_text(result, encoding="utf-8")
