"""doclint - the documentation style gate of docs/style.md, as a ratchet.

    python tools/quality/doclint.py                      # the gate (quick.ps1 runs this)
    python tools/quality/doclint.py --files docs/build.md # the findings of named files
    python tools/quality/doclint.py --list                # baseline lines, for a human to review
    python tools/quality/doclint.py --prune              # lower the baseline to what the docs have now

The rules are in `docs/style.md`. Two sources of findings:

  - the vendored ASD-STE100 structural linter, `third_party/ste_lint.py`. Its "advisory-free"
    findings count; its advisory findings (passive voice, compound tenses) never do.
  - the project rules of this file: no em dash or en dash in prose, and no spelling that
    `docs/glossary.yaml` names under `instead_of`. One term, one meaning.

The gate is a ratchet, not a rewrite order. `doclint_baseline.txt` records the count each
document had when the gate landed. The gate fails when

  - a document in the baseline has more findings than its line allows, or
  - a document outside the baseline has any finding at all (a new document starts clean).

It passes, with a note to lower or remove the line, when a document improves or leaves the
tree. Nothing raises a baseline line by itself: --list prints candidate lines for review and
--prune only lowers and removes. --prune refuses to touch the file while the gate fails.

Scope: README.md, everything under docs/, and every Markdown file under driver/ and tools/.
Out of scope: evidence/ (immutable), experiments/ (the record of one run), generated pages
(a `*.generated.md` name or the "GENERATED by" banner), and this repository's third_party
imports, which are somebody else's text.
"""
import argparse
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent / 'third_party'))
import ste_lint                                                   # noqa: E402  (vendored)

BASELINE = 'tools/quality/doclint_baseline.txt'
GLOSSARY = 'docs/glossary.yaml'

ROOTS = ('docs', 'driver', 'tools')
TOP_LEVEL = ('README.md',)
SKIP_DIRS = ('third_party',)
GENERATED = re.compile(r'GENERATED by |^Generated by `tools/', re.M)

DASHES = {'—': 'em dash', '–': 'en dash'}


class GlossaryError(Exception):
    pass


# ------------------------------------------------------------------ the glossary

def load_glossary(path):
    """Read docs/glossary.yaml: the strict subset the repository's own files use.

    terms:
      - term: adapter
        means: "one meaning, in one sentence"
        instead_of: ["graphics card", "video card"]

    No pyyaml: the facts graph parses its own data files the same way, and CI installs
    nothing. Anything outside the subset is an error, never a silently ignored line.
    """
    terms = []
    term = None
    for n, line in enumerate(pathlib.Path(path).read_text(encoding='utf-8').split('\n'), 1):
        where = f'{path}:{n}'
        if not line.strip() or line.lstrip().startswith('#'):
            continue
        if line == 'terms:':
            continue
        m = re.match(r'^  - term: (.+)$', line)
        if m:
            term = {'term': m.group(1).strip(), 'means': '', 'instead_of': []}
            terms.append(term)
            continue
        m = re.match(r'^    (means|instead_of):(.*)$', line)
        if not m or term is None:
            raise GlossaryError(f'{where}: not a glossary line: {line[:60]}')
        key, rest = m.group(1), m.group(2).strip()
        if key == 'means':
            try:
                term['means'] = json.loads(rest)
            except json.JSONDecodeError as e:
                raise GlossaryError(f'{where}: means takes a "quoted string" ({e})')
        else:
            try:
                value = json.loads(rest)
            except json.JSONDecodeError as e:
                raise GlossaryError(f'{where}: instead_of takes a JSON list of strings ({e})')
            if not isinstance(value, list) or not all(isinstance(v, str) and v for v in value):
                raise GlossaryError(f'{where}: instead_of takes a JSON list of strings')
            term['instead_of'] = value
    for term in terms:
        if not term['means']:
            raise GlossaryError(f'{path}: term {term["term"]!r} has no means')
    if not terms:
        raise GlossaryError(f'{path}: no terms')
    return terms


def glossary_rules(terms):
    """One compiled pattern a banned spelling, with the term that replaces it."""
    rules = []
    for term in terms:
        for spelling in term['instead_of']:
            # Lookarounds, not \b: "e.g." ends in a dot, where \b never matches.
            pattern = re.compile(r'(?<!\w)' + r'\s+'.join(re.escape(w) for w in spelling.split())
                                 + r'(?!\w)', re.I)
            rules.append((pattern, spelling, term['term']))
    return rules


# ------------------------------------------------------------------ project findings

def project_findings(text, filename, rules):
    """The rules of this file: dashes and glossary spellings, in prose only.

    Code fences and inline code are operands, not prose, exactly as the vendored linter
    treats them: a dash inside a command line or a banned word inside an identifier is not
    a style mistake.
    """
    findings = []
    in_fence = False
    for lineno, raw_line in enumerate(text.splitlines(), 1):
        if ste_lint.CODE_FENCE.match(raw_line.strip()):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        # Keep the columns of the surviving text by blanking the code spans in place.
        line = ste_lint.INLINE_CODE.sub(lambda m: ' ' * len(m.group(0)), raw_line)
        for char, name in DASHES.items():
            for column, c in enumerate(line, 1):
                if c == char:
                    findings.append({
                        'file': filename, 'line': lineno, 'col': column,
                        'rule': 'dash', 'level': 'advisory-free', 'match': char,
                        'message': f'{name} in prose. Use a plain hyphen - (docs/style.md).'})
        for pattern, spelling, term in rules:
            for m in pattern.finditer(line):
                findings.append({
                    'file': filename, 'line': lineno, 'col': m.start() + 1,
                    'rule': 'glossary', 'level': 'advisory-free', 'match': m.group(0),
                    'message': f'{spelling!r} is this project\'s {term!r} (docs/glossary.yaml). '
                               f'Use {term!r} every time.'})
    return findings


def findings_for(path, rules, filename=None):
    """Every hard finding of one document, in document order."""
    text = path.read_text(encoding='utf-8')
    name = filename if filename is not None else str(path)
    hard, _ = ste_lint.lint(text, name)
    hard = [f for f in hard if f['level'] == 'advisory-free']
    hard.extend(project_findings(text, name, rules))
    hard.sort(key=lambda f: (f['line'], f['col'], f['rule']))
    return hard


# ------------------------------------------------------------------ scope and baseline

def in_scope(root):
    """The documents the gate reads, as repository-relative posix paths, sorted."""
    paths = [root / name for name in TOP_LEVEL]
    for top in ROOTS:
        paths.extend(sorted((root / top).rglob('*.md')))
    found = []
    for path in paths:
        if not path.is_file():
            continue
        relative = path.relative_to(root).as_posix()
        if any(part in SKIP_DIRS for part in path.relative_to(root).parts):
            continue
        if path.name.endswith('.generated.md'):
            continue
        if GENERATED.search(path.read_text(encoding='utf-8')[:2000]):
            continue
        found.append(relative)
    return sorted(set(found))


def read_baseline(path):
    allowance = {}
    for n, line in enumerate(pathlib.Path(path).read_text(encoding='utf-8').split('\n'), 1):
        if not line.strip() or line.startswith('#'):
            continue
        parts = line.split('\t')
        if len(parts) != 2 or not parts[0].strip().isdigit():
            raise GlossaryError(f'{path}:{n}: expected "<count><tab><path>": {line[:60]}')
        allowance[parts[1].strip()] = int(parts[0])
    return allowance


def write_baseline(path, header, counts):
    lines = list(header)
    lines.extend(f'{counts[name]}\t{name}' for name in sorted(counts))
    pathlib.Path(path).write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')


def baseline_header(path):
    """The comment block at the top of the baseline file, kept across a rewrite."""
    header = []
    for line in pathlib.Path(path).read_text(encoding='utf-8').split('\n'):
        if line.startswith('#') or not line.strip():
            header.append(line)
            continue
        break
    while header and not header[-1].strip():
        header.pop()
    return header


# ------------------------------------------------------------------ main

def main(argv=None):
    here = pathlib.Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0],
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--root', default=str(here.parent.parent), help='the repository root')
    parser.add_argument('--baseline', default=None)
    parser.add_argument('--glossary', default=None)
    parser.add_argument('--out', default=None, help='directory for doclint.json')
    parser.add_argument('--files', nargs='+', default=None,
                        help='report these documents and exit, without the ratchet')
    parser.add_argument('--list', action='store_true', help='baseline lines, for review')
    parser.add_argument('--prune', action='store_true',
                        help='lower the baseline to the counts the documents have now')
    args = parser.parse_args(argv)

    root = pathlib.Path(args.root).resolve()
    baseline_path = pathlib.Path(args.baseline) if args.baseline else root / BASELINE
    glossary_path = pathlib.Path(args.glossary) if args.glossary else root / GLOSSARY
    rules = glossary_rules(load_glossary(glossary_path))

    if args.files:
        bad = 0
        for name in args.files:
            path = pathlib.Path(name)
            found = findings_for(path, rules, filename=path.as_posix())
            for f in found:
                print(f'{f["file"]}:{f["line"]}:{f["col"]} {f["rule"]}: {f["message"]} [{f["match"]}]')
            print(f'{path.as_posix()}: {len(found)} findings')
            bad += len(found)
        return 1 if bad else 0

    counts = {name: len(findings_for(root / name, rules, filename=name))
              for name in in_scope(root)}

    if args.list:
        for name in sorted(counts):
            if counts[name]:
                print(f'{counts[name]}\t{name}')
        return 0

    allowance = read_baseline(baseline_path)
    worse, new, better, gone = [], [], [], []
    for name, count in sorted(counts.items()):
        if name not in allowance:
            if count:
                new.append((name, count))
        elif count > allowance[name]:
            worse.append((name, count, allowance[name]))
        elif count < allowance[name]:
            better.append((name, count, allowance[name]))
    gone = sorted(name for name in allowance if name not in counts)

    if args.prune:
        if worse or new:
            print('the gate fails: fix the documents below before you prune the baseline')
        else:
            kept = {name: counts[name] for name in allowance if counts.get(name)}
            write_baseline(baseline_path, baseline_header(baseline_path), kept)
            print(f'{baseline_path}: {len(kept)} lines, {len(better)} lowered, '
                  f'{len(allowance) - len(kept)} removed')
            return 0

    for name, count, allowed in better:
        print(f'note: {name} is down to {count} from {allowed}. Lower its baseline line (--prune).')
    for name in gone:
        print(f'note: {name} is no longer in the tree. Remove its baseline line (--prune).')

    if worse or new:
        for name, count in new:
            print(f'FAIL {name}: {count} findings, and a document outside the baseline '
                  f'must have none')
        for name, count, allowed in worse:
            print(f'FAIL {name}: {count} findings, {allowed} allowed')
        print()
        for name in [n for n, _ in new] + [n for n, _, _ in worse]:
            for f in findings_for(root / name, rules, filename=name):
                print(f'{f["file"]}:{f["line"]}:{f["col"]} {f["rule"]}: {f["message"]} '
                      f'[{f["match"]}]')
        print('\ndocs/style.md states the rules. The baseline never rises: fix the text.')
        status = 'FAIL'
    else:
        print(f'{len(counts)} documents, {sum(counts.values())} findings, '
              f'{len(allowance)} baseline lines, {len(better)} below the line, '
              f'{len(gone)} gone')
        status = 'PASS'

    if args.out:
        out = pathlib.Path(args.out)
        out.mkdir(parents=True, exist_ok=True)
        (out / 'doclint.json').write_text(json.dumps(
            {'status': status, 'documents': counts, 'baseline': allowance,
             'worse': worse, 'new': new, 'better': better, 'gone': gone},
            indent=2), encoding='utf-8')
    return 1 if status == 'FAIL' else 0


if __name__ == '__main__':
    sys.exit(main())
