#!/usr/bin/env python3
"""gen_regs.py - the register sets of gpu-timeline.exe, as a C header, from tools/regcalc.

    python tools/win/gpu-timeline/gen_regs.py [--repo <this repository>] [--out gtl_regs.h]

Every BAR5 offset comes from regcalc (bc250-win rule 1). Every offset must also be in bc250rd's own allow-list
(tools/win/bc250rd/driver/allowlist.h), because the driver refuses a whole batch when one offset is not; and no name
may match the registers whose read changes state (facts M25: *_HEADER_DUMP, *INVALIDATE_ENG*_SEM, GRBM_GFX_CNTL).

Read order inside one sample matters: GRBM_STATUS first and again last, so the analyzer can tell a sample whose
GPU state changed during the ~20 us of reads (the "bracket").
"""
import argparse
import re
import sys
from pathlib import Path

# bc250-win/tools/win/gpu-timeline/gen_regs.py: the repository root is three levels up.
DEFAULT_REPO = Path(__file__).resolve().parents[3]

# The full set: block busy (GRBM), CP state (CP_STAT, CP_BUSY_STAT, CP_STALLED_STAT1-3), command fetch (CPF), the copy
# engines, ring progress, and GRBM_STATUS again as the closing bracket.
FULL = [
    "GRBM_STATUS", "GRBM_STATUS2", "GRBM_STATUS3", "GRBM_STATUS_SE0", "GRBM_STATUS_SE1",
    "CP_STAT", "CP_BUSY_STAT", "CP_STALLED_STAT1", "CP_STALLED_STAT2", "CP_STALLED_STAT3",
    "CP_CPF_STATUS", "CP_CPF_BUSY_STAT", "CP_CPF_STALLED_STAT1",
    "SDMA0_STATUS_REG", "SDMA1_STATUS_REG", "CP_RB0_RPTR",
    "GRBM_STATUS",
]
# Fewer reads per sample, for a higher rate or a lower cost.
LITE = [
    "GRBM_STATUS", "GRBM_STATUS2", "GRBM_STATUS_SE0", "GRBM_STATUS_SE1",
    "CP_STAT", "CP_BUSY_STAT", "CP_STALLED_STAT1", "CP_STALLED_STAT2",
    "GRBM_STATUS",
]
# Read once at the start and once at the end of a run: the GRBM bank the banked registers answer for.
ONCE = ["GRBM_GFX_INDEX"]

DENY = re.compile(r"HEADER_DUMP|INVALIDATE_ENG\d+_SEM|GRBM_GFX_CNTL")


def load_allow(path):
    text = Path(path).read_text(encoding="utf-8")
    body = text[text.index("g_Allow["):]
    return {int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]+)", body)}


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", default=str(DEFAULT_REPO))
    ap.add_argument("--out", default=str(Path(__file__).resolve().parent / "gtl_regs.h"))
    args = ap.parse_args(argv)
    repo = Path(args.repo)
    sys.path.insert(0, str(repo / "tools" / "regcalc"))
    import regcalc  # noqa: E402

    rm = regcalc.RegMap()
    allow = load_allow(repo / "tools" / "win" / "bc250rd" / "driver" / "allowlist.h")
    errors = []

    def offset(name):
        mm = "mm" + name
        if mm not in rm.regs:
            errors.append(f"{name}: not in regcalc's header")
            return 0
        off = rm.byte_offset(mm)
        if DENY.search(name):
            errors.append(f"{name}: read has side effects (facts M25)")
        if off not in allow:
            errors.append(f"{name} 0x{off:05X}: not in bc250rd's allow-list")
        return off

    lines = [
        "// Generated by gen_regs.py through tools/regcalc; checked against bc250rd's allowlist.h. Do not edit.",
        "#pragma once",
        "",
        "typedef struct _GTL_REG { unsigned long Offset; const char* Name; } GTL_REG;",
        "",
    ]
    for set_name, regs in (("FULL", FULL), ("LITE", LITE)):
        lines.append(f"#define GTL_{set_name}_COUNT {len(regs)}")
        lines.append(f"static const GTL_REG g_Gtl{set_name.title()}[GTL_{set_name}_COUNT] = {{")
        for name in regs:
            lines.append(f"    {{ 0x{offset(name):05X}ul, \"{name}\" }},")
        lines.append("};")
        lines.append("")
    for name in ONCE:
        lines.append(f"#define GTL_REG_{name} 0x{offset(name):05X}ul")
    lines.append("")
    if errors:
        for e in errors:
            print("ERROR", e, file=sys.stderr)
        return 1
    Path(args.out).write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {args.out}: full {len(FULL)}, lite {len(LITE)}, once {len(ONCE)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
