// Generated by gen_regs.py through tools/regcalc; checked against bc250rd's allowlist.h. Do not edit.
#pragma once

typedef struct _GTL_REG { unsigned long Offset; const char* Name; } GTL_REG;

#define GTL_FULL_COUNT 17
static const GTL_REG g_GtlFull[GTL_FULL_COUNT] = {
    { 0x08010ul, "GRBM_STATUS" },
    { 0x08008ul, "GRBM_STATUS2" },
    { 0x0801Cul, "GRBM_STATUS3" },
    { 0x08014ul, "GRBM_STATUS_SE0" },
    { 0x08018ul, "GRBM_STATUS_SE1" },
    { 0x08680ul, "CP_STAT" },
    { 0x0867Cul, "CP_BUSY_STAT" },
    { 0x08674ul, "CP_STALLED_STAT1" },
    { 0x08678ul, "CP_STALLED_STAT2" },
    { 0x08670ul, "CP_STALLED_STAT3" },
    { 0x0821Cul, "CP_CPF_STATUS" },
    { 0x08220ul, "CP_CPF_BUSY_STAT" },
    { 0x08224ul, "CP_CPF_STALLED_STAT1" },
    { 0x04A14ul, "SDMA0_STATUS_REG" },
    { 0x06214ul, "SDMA1_STATUS_REG" },
    { 0x08700ul, "CP_RB0_RPTR" },
    { 0x08010ul, "GRBM_STATUS" },
};

#define GTL_LITE_COUNT 9
static const GTL_REG g_GtlLite[GTL_LITE_COUNT] = {
    { 0x08010ul, "GRBM_STATUS" },
    { 0x08008ul, "GRBM_STATUS2" },
    { 0x08014ul, "GRBM_STATUS_SE0" },
    { 0x08018ul, "GRBM_STATUS_SE1" },
    { 0x08680ul, "CP_STAT" },
    { 0x0867Cul, "CP_BUSY_STAT" },
    { 0x08674ul, "CP_STALLED_STAT1" },
    { 0x08678ul, "CP_STALLED_STAT2" },
    { 0x08010ul, "GRBM_STATUS" },
};

#define GTL_REG_GRBM_GFX_INDEX 0x30800ul
